"""Content for /australia/corrective-jaw-surgery/ — Top 10 Corrective Jaw Surgery in Australia.
Generated by service_pipeline.py (2026-08-23)."""
import json

META_TITLE = "** Corrective Jaw Surgery Australia – Top 10 Clinics (2025)"
META_DESC = "Compare the top 10 corrective jaw surgery in Australia."
H1 = "Top 10 Corrective Jaw Surgery in Australia"
BADGE = "Top 10 — Reviewed & Ranked"

INTRO = [
    "Corrective jaw surgery — also called orthognathic surgery — repositions the upper jaw (maxilla), lower jaw (mandible), or both to correct skeletal and dental irregularities. In Australia, this surgery is performed by specialist oral and maxillofacial surgeons in a hospital under general anaesthetic. It is used to treat severe underbites, overbites, crossbites, open bites, obstructive sleep apnoea, TMJ pain, facial asymmetry, and jaw problems caused by trauma or cleft conditions.",
    "This page reviews and ranks the top 10 corrective jaw surgery providers in Australia. We compared each practice against eight ranking criteria, including specialist credentials, surgical experience, hospital access, multidisciplinary care, and transparency of fees. We also include typical Australian costs, Medicare rebates, private health insurance tips, recovery timelines, and answers to the most common questions about corrective jaw surgery. If you are just starting your research, explore our <a href=\"/australia/\">guide to dental care in Australia</a> or go straight to the <a href=\"#top-10-corrective-jaw-surgery-clinics-in-australia\">ranked list of surgeons</a>.",
    'Positions 1 to 3 are paid placements with do-follow links. Positions 4 to 10 are editorial selections with no-follow links. Browse our complete directory of <a href="/australia/">all dental services across Australia</a>. Read <a href="/methodology/">our methodology</a> and our <a href="/disclosures/">disclosures policy</a> for full transparency.',
]

WHEN_HEADING = "When do you need it?"
WHEN = [
    "When placeholder.",
]

WHEN_ALERT = "If you have severe pain, uncontrolled bleeding, or facial swelling that affects breathing or vision, call 000 or go to the nearest hospital emergency department immediately."

WHO_HEADING = "Which are the top 10 corrective jaw surgery in Australia?"
WHO_TOP10 = "The ten clinics below are ranked from 1 to 10. Ranks 1-3 are featured entries."

TOP10 = [
    {"rank": 1, "name": "Placeholder Clinic", "location": "Australia", "featured": True, "rating": "", "pricing": "", "hours": "", "address": "", "phone": "", "website": "", "body": [""]},
]

COST_HEADING = "Cost of Corrective Jaw Surgery in Australia"
COST = [
    "Corrective jaw surgery is a major procedure, and the total cost depends on the surgeon, hospital, anaesthetist, orthodontic treatment, and your private health insurance cover. In Australia, most patients have some costs covered by Medicare and private health insurance, but patients often face a significant out-of-pocket gap.",
    "<strong>Funding note:</strong> Medicare covers 75% of the MBS scheduled fee for orthognathic surgery (MBS item numbers 45617–45998). Private health insurance with top hospital cover is usually required to cover hospital and anaesthetist fees, and most major funds offer “no gap” or “known gap” arrangements for eligible patients. Orthodontics is not covered by Medicare, although private health funds may provide a rebate of roughly $1,000–$2,500. Always ask the surgeon’s office for a written itemised quote before proceeding. For related cost information, see our <a href=\"/australia/oral-surgery/\">oral surgery guide</a>.",
]
COST_PRICES = [
    ("Orthodontics (pre & post)", "$5,000 – $10,000"),
    ("Total estimated cost", "**$15,000 – $40,000+**"),
]
COST_AFTER = [
    'See our <a href="/blog/costs/">dental costs guide</a> for full fee breakdowns.',
]

CHOOSE_HEADING = "How to Choose a Corrective Jaw Surgery Provider in Australia"
CHOOSE_INTRO = "Ask these questions before you book."
CHOOSE_CRITERIA = [
    ("Are you a registered specialist oral and maxillofacial surgeon?", "Look for a surgeon with FRACDS (OMS) or equivalent specialist qualification, and membership with the Australian and New Zealand Association of Oral and Maxillofacial Surgeons (ANZAOMS)."),
    ("How many orthognathic cases do you perform each year?", "High-volume surgeons tend to have better outcomes and lower complication rates. Ask for their experience with your specific jaw deformity."),
    ("What exactly does the quoted fee include?", "A comprehensive quote should include the surgeon’s fee, anaesthetist’s fee, hospital fee, initial consultations, and follow-up appointments. Ask what is not included."),
    ("Do you work closely with my orthodontist?", "Corrective jaw surgery almost always requires braces before and after surgery. A good surgeon will coordinate closely with your orthodontist to plan the entire treatment timeline."),
    ("What are the risks, and how do you manage complications?", "Your surgeon should clearly explain the risk of nerve damage, infection, relapse, and non-union, and how they manage these if they occur. Use our <a href=\"/australia/dentists/\">Australian dentist directory</a> to find qualified specialists, or explore related services like <a href=\"/australia/orthodontics/\">orthodontics</a> and <a href=\"/australia/sleep-apnoea/\">sleep apnoea treatment</a>."),
]
CHOOSE_AFTER = []

METHODOLOGY_HEADING = "Methodology: How We Ranked These Clinics"
METHODOLOGY = [
    "We ranked these clinics using the criteria below."
]
METHODOLOGY_CRITERIA = [
    "We ranked each practice using 8 criteria:",
    "Specialist qualifications — verification of FRACDS (OMS) or equivalent and ANZAOMS membership.",
    "Orthognathic surgery volume — the number of corrective jaw cases performed regularly by the practice.",
    "Scope of procedures — including maxillary osteotomy, BSSO, bimaxillary osteotomy, genioplasty, and segmental osteotomy.",
    "Multidisciplinary care — coordination with orthodontists, physiotherapists, speech pathologists, and sleep physicians.",
    "Hospital and facility access — private hospital admission and modern theatre facilities.",
    "Patient support and follow-up — clear pre-operative planning, post-operative reviews, and emergency access.",
    "Accessibility and location — availability of multiple consulting rooms or regional coverage.",
    "Fee transparency — willingness to provide itemised quotes and insurance information.",
    "These criteria are designed to give a balanced view of clinical excellence and patient experience. Rankings may change over time as practices update their services and staff.",
]
METHODOLOGY_AFTER = []

FAQ_HEADING = "Frequently Asked Questions"
FAQS = [
    ("Does Medicare cover corrective jaw surgery?", "Yes, Medicare covers 75% of the MBS scheduled fee for the surgeon. Hospital and anaesthetist fees are usually covered by private health insurance if you have top hospital cover. Orthodontics is not covered by Medicare, but health funds may pay a rebate. Explore our <a href=\"/australia/\">Australia dental hub</a> for more information on Medicare and dental coverage."),
    ("Do I need braces before and after jaw surgery?", "Yes, almost all patients need orthodontic treatment before and after corrective jaw surgery. Braces align the teeth to the new jaw position over 12–18 months before surgery and 6–12 months after surgery. Learn more about the orthodontic process on our <a href=\"/australia/orthodontics/\">orthodontics page</a>."),
    ("How long is the recovery time for jaw surgery?", "Most patients take 2–4 weeks off work or school, follow a soft diet for about 6 weeks, and see most swelling resolve within 3 months. Full bone healing takes around 12 months. Recovery times vary depending on the complexity of the procedure. For a broader look at recovery, see our <a href=\"/australia/oral-surgery/\">oral surgery guide</a>."),
    ("What are the risks of corrective jaw surgery?", "The main risks include temporary or permanent nerve damage, infection, bleeding, relapse, non-union of the bone, and complications from general anaesthetic. The chance of permanent significant numbness in the lower lip or chin is around 1–2%. Your surgeon will discuss these risks in detail during your consultation. Review our <a href=\"/australia/\">Australia dental hub</a> for more information on surgical risks."),
    ("Can I get jaw surgery for sleep apnoea?", "Yes. Maxillomandibular advancement (MMA) is a highly effective surgical treatment for moderate to severe obstructive sleep apnoea when CPAP therapy has failed or is not tolerated. A surgeon will assess your airway and jaw position to decide if MMA is appropriate. See our <a href=\"/australia/sleep-apnoea/\">sleep apnoea treatment page</a> for more details."),
    ("What is the best age for jaw surgery?", "Most patients are between 18 and 40 years old, after the jaw has stopped growing — around 16 for females and 18 for males. Older adults can also have corrective jaw surgery, but healing and recovery may take longer. Read more about treatment timing in our <a href=\"/australia/orthodontics/\">orthodontics guide</a>."),
    ("How do I find a qualified surgeon for corrective jaw surgery in Australia?", "Look for a registered specialist oral and maxillofacial surgeon with FRACDS (OMS) or equivalent qualification and membership with ANZAOMS. You can also use the <a href=\"/australia/dentists/\">Australian dentist directory</a> to find experienced providers near you."),
]

CTA_TITLE = "Are you an Corrective Jaw Surgery provider in Australia?"
CTA_TEXT = "Apply to be featured in our next update."

DISCLOSURE = "Practices in positions 1 to 3 are paid placements with do-follow links. Practices in positions 4 to 10 are listed editorially with no-follow links. Paid placement never affects positions 4 to 10."

SCHEMAS = []  # built by the template's _build_schemas() in manual workflow