"""Content for /australia/corrective-jaw-surgery/ — Top 10 Corrective Jaw Surgery in Australia.
Rewritten 2026-08-24 with REAL verified clinic data (all 10 websites resolve, addresses/phones verified on live practice sites)."""
import json

META_TITLE = "Corrective Jaw Surgery Australia – Top 10 Clinics"
META_DESC = "Compare the top 10 corrective jaw surgery providers in Australia."

H1 = "Top 10 Corrective Jaw Surgery in Australia"
BADGE = "Top 10 — Reviewed & Ranked"

INTRO = [
    "Corrective jaw surgery — also called orthognathic surgery — repositions the upper jaw (maxilla), lower jaw (mandible), or both to correct skeletal and dental irregularities. In Australia, this surgery is performed by specialist oral and maxillofacial surgeons in a hospital under general anaesthetic. It is used to treat severe underbites, overbites, crossbites, open bites, obstructive sleep apnoea, TMJ pain, facial asymmetry, and jaw problems caused by trauma or cleft conditions.",
    "This page reviews and ranks the top 10 corrective jaw surgery providers in Australia. We compared each practice against eight ranking criteria, including specialist credentials, surgical experience, hospital access, multidisciplinary care, and transparency of fees. We also include typical Australian costs, Medicare rebates, private health insurance tips, recovery timelines, and answers to the most common questions about corrective jaw surgery. If you are just starting your research, explore our <a href=\"/australia/\">guide to dental care in Australia</a> or go straight to the <a href=\"#top-10-corrective-jaw-surgery-clinics-in-australia\">ranked list of surgeons</a>.",
    'Positions 1 to 3 are paid placements with do-follow links. Positions 4 to 10 are editorial selections with no-follow links. Browse our complete directory of <a href="/australia/">all dental services across Australia</a>. Read <a href="/methodology/">our methodology</a> and our <a href="/disclosures/">disclosures policy</a> for full transparency.',
]

WHEN_HEADING = "When Should You Consider Corrective Jaw Surgery in Australia?"
WHEN = [
    "You may need corrective jaw surgery if you have any of the following functional issues:",
    "A specialist oral and maxillofacial surgeon can confirm whether you are a candidate using X-rays, 3D scans, orthodontic records, and airway analysis. Most patients are referred by an orthodontist or general dentist. If you need a professional to start with, browse the <a href=\"/australia/\">Australian dentist directory</a> or read about <a href=\"/australia/orthodontist/\">orthodontic treatment</a>.",
]

WHEN_ALERT = "If you have severe pain, uncontrolled bleeding, or facial swelling that affects breathing or vision, call 000 or go to the nearest hospital emergency department immediately."

WHO_HEADING = "Which are the top 10 corrective jaw surgery providers in Australia?"
WHO_TOP10 = "The ten clinics below are ranked from 1 to 10. Ranks 1-3 are featured entries."

TOP10 = [
    {"rank": 1, "name": "Sydney Oral & Maxillofacial Surgery (SOMS)", "location": "Sydney, NSW", "featured": True, "rating": "9.8/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 8:00am\u20134:00pm", "address": "Suite 1401, Level 14, Tower 1, 520 Oxford Street, Bondi Junction NSW 2022", "phone": "(02) 9369 2153", "website": "https://soms.com.au", "body": ["Sydney Oral & Maxillofacial Surgery (SOMS) is one of the largest dedicated OMS groups in New South Wales. The practice includes specialist surgeons Dr Michael Cooper, Dr Paul Hammans, and Dr S C McEachen, who collectively manage the full spectrum of orthognathic surgery, facial trauma, and TMJ disorders. In our review, this practice stood out for its high-volume corrective jaw surgery caseload, Bondi Junction location, and strong collaboration with referring orthodontists.", "The team treats maxillary hypoplasia, mandibular prognathism, facial asymmetry, and obstructive sleep apnoea using modern 3D surgical planning. Patients benefit from close coordination with specialists in <a href=\"/australia/tmj-treatment/\">TMJ disorders</a> and <a href=\"/australia/sleep-apnoea-treatment/\">sleep apnoea treatment</a>. For a local view of surgeons and services, explore our <a href=\"/australia/sydney/\">Sydney dental guide</a>."]},
    {"rank": 2, "name": "Melbourne Oral and Maxillofacial Surgery", "location": "Melbourne, VIC", "featured": True, "rating": "9.7/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 8:00am\u20135:00pm", "address": "Level 6, 120 Collins Street, Melbourne VIC 3000", "phone": "(03) 9088 8666", "website": "https://melbourneoms.com.au", "body": ["Melbourne Oral and Maxillofacial Surgery is a high-volume centre for orthognathic surgery and temporomandibular joint treatment. The practice is led by specialist surgeons Prof Andrew Heggie, Mr Kevin Ruljancich, and A/Prof Jocelyn Shand, who work together to treat complex jaw deformities and maxillofacial conditions. The group has a CBD main office plus locations in Bundoora and Hawthorn East, making it one of the most accessible OMS groups in Victoria.", "The team provides the full spectrum of corrective jaw procedures, including maxillary osteotomy, mandibular BSSO, bimaxillary osteotomy, and genioplasty. Because the practice also specialises in TMJ surgery, it is particularly well suited to patients whose jaw misalignment is linked to joint pain. You can find more Victorian-focused resources on our <a href=\"/australia/melbourne/\">Melbourne dental guide</a>."]},
    {"rank": 3, "name": "Faciomax", "location": "Brisbane, QLD", "featured": True, "rating": "9.6/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 8:30am\u20135:00pm", "address": "149 Wickham Terrace, Spring Hill QLD 4000", "phone": "(07) 3724 0319", "website": "https://faciomax.com", "body": ["Faciomax is a specialist oral and maxillofacial surgery practice serving Brisbane and South-East Queensland. The team includes ANZAOMS-accredited surgeons who treat a wide variety of diseases and injuries of the mouth, teeth, jaws, and face. The practice is known for its thorough pre-operative assessment, use of 3D imaging and surgical planning, and close collaboration with orthodontists for both pre- and post-surgical orthodontic care.", "Faciomax offers the full scope of orthognathic surgery, including maxillary and mandibular osteotomies and bimaxillary procedures. Patients travel from regional Queensland for treatment. To see other practices in the state, visit our <a href=\"/australia/brisbane/\">Brisbane dental guide</a>."]},
    {"rank": 4, "name": "Oral Surgery Consultants", "location": "Perth, WA", "featured": False, "rating": "9.5/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 8:00am\u20135:30pm", "address": "99 Outram Street, West Perth WA 6005", "phone": "(08) 6468 4948", "website": "https://osconsultants.com.au", "body": ["Oral Surgery Consultants is a specialist OMS practice serving Western Australia and the Northern Territory. The surgical team is led by Dr Leon Smith, a dual-qualified specialist oral and maxillofacial surgeon, and provides comprehensive orthognathic surgery, dental implant treatment, and facial trauma care. The practice has a dedicated orthognathic (jaw) surgery service and is a major referral centre for the state.", "The team regularly treats patients with severe bite problems, jaw asymmetry, sleep apnoea, and TMJ disorders. Because Western Australia has fewer specialist OMS providers, the practice acts as a key referral centre with consulting rooms in West Perth and Darwin. You can explore more local options on our <a href=\"/australia/perth/\">Perth dental guide</a>."]},
    {"rank": 5, "name": "Advanced Oral & Maxillofacial Surgery", "location": "Adelaide, SA", "featured": False, "rating": "9.4/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 9:00am\u20135:00pm", "address": "238 Angas Street, Adelaide SA 5000", "phone": "(08) 8272 7399", "website": "https://advancedoms.com.au", "body": ["Advanced Oral & Maxillofacial Surgery (AOMS) has delivered expert surgical care in South Australia since 2016. With a state-of-the-art day surgery facility, AOMS combines innovation, advanced technology, and compassionate care. The team provides the full scope of oral and maxillofacial surgery, including orthognathic (corrective jaw) procedures, dental implants, and surgical treatment of oral pathology.", "In addition to corrective jaw surgery, the practice provides treatment for oral pathology, facial trauma, and TMJ dysfunction. The team works closely with orthodontists to plan surgery around braces and bite correction. You can find additional South Australian dental resources on our <a href=\"/australia/adelaide/\">Adelaide dental guide</a>."]},
    {"rank": 6, "name": "Gold Coast Oral, Maxillofacial & Implant Surgery", "location": "Gold Coast, QLD", "featured": False, "rating": "9.3/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 8:30am\u20135:00pm", "address": "Suite 301, Pindara Specialist Suites, 29 Carrara Street, Benowa QLD 4217", "phone": "(07) 5527 8858", "website": "https://goldcoastoms.com.au", "body": ["Gold Coast Oral, Maxillofacial & Implant Surgery is a well-established OMS practice led by Dr Shannon Webber, a leader in oral and maxillofacial surgery with over a decade of experience as a Visiting Specialist Surgeon at Gold Coast University Hospital. The practice offers the full scope of OMS procedures, including corrective jaw surgery (orthognathic surgery), dental implants, wisdom teeth removal, and facial trauma care.", "Dr Webber was the Supervisor of Training and Gold Coast Representative on the Regional Surgical Committee affiliated with the Queensland OMS training program. The practice lists Corrective Jaw Surgery (Orthognathic Surgery) as a dedicated procedure. Patients from the Gold Coast, Tweed Heads, and Northern Rivers choose this practice for its accessible location and comprehensive care. See our Gold Coast dental guide for more local information."]},
    {"rank": 7, "name": "Canberra Oral & Maxillofacial Centre", "location": "Canberra, ACT", "featured": False, "rating": "9.2/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 8:30am\u20135:00pm", "address": "Suite 14, Level 3, Francis Chambers, 40\u201342 Corinna Street, Phillip ACT 2606", "phone": "(02) 5110 3032", "website": "https://canberraomfc.com.au", "body": ["Canberra Oral & Maxillofacial Centre is led by Dr Ragu Krishnamoorthy, a specialist oral and maxillofacial surgeon serving the ACT and surrounding region. The practice provides a full-scope OMS service including orthognathic (corrective jaw) surgery, dental implants, wisdom teeth removal, sinus lifts, facial trauma surgery, oral pathology, and TMJ disorders. The centre is located in Woden, close to Canberra's private and public hospitals.", "Dr Krishnamoorthy is a member of the Royal Australasian College of Dental Surgeons, Australian Dental Association, ANZAOMS, and the Australian Medical Association. The practice offers thorough pre-surgical orthodontic coordination, 3D imaging, and post-surgical rehabilitation. For patients in the national capital area, this practice offers convenient access to specialist care without travelling interstate. Find more regional NSW/ACT resources on our <a href=\"/australia/canberra/\">Canberra dental guide</a>."]},
    {"rank": 8, "name": "Wood Street Specialists", "location": "Newcastle, NSW", "featured": False, "rating": "9.1/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 8:30am\u20135:00pm", "address": "18 Wood Street, Newcastle West NSW 2302", "phone": "(02) 4023 5504", "website": "https://woodstreetspecialists.com.au", "body": ["Wood Street Specialists is the Hunter region's principal specialist practice for corrective jaw surgery and oral and maxillofacial surgery. Specialist surgeons Dr Patrick Mehanna and Dr Bobby Yang provide a comprehensive range of procedures including corrective jaw surgery, wisdom teeth extractions, dental implants, bone grafting, TMJ disorders, oral pathology, and microsurgery. The practice is conveniently located in Newcastle West.", "Wood Street Specialists has a dedicated Corrective Jaw Surgery procedure page and offers thorough pre-surgical planning, 3D imaging, and close coordination with orthodontists. This practice is an important option for patients in regional New South Wales who need high-level surgical care close to home. To find more dentists and specialists, use the <a href=\"/australia/\">Australian dentist directory</a>."]},
    {"rank": 9, "name": "Dimitroulis and Associates", "location": "Melbourne, VIC", "featured": False, "rating": "9.0/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 8:30am\u20135:00pm", "address": "Suite 1, Ground Floor, Epworth Freemasons, 124 Grey Street, East Melbourne VIC 3002", "phone": "(03) 9654 3799", "website": "https://dimitroulis.com", "body": ["Dimitroulis and Associates is led by Dr George Dimitroulis, an internationally recognised oral and maxillofacial surgeon known for his expertise in TMJ surgery and complex orthognathic reconstruction. Based in the Epworth Freemasons building in East Melbourne, the practice attracts patients with complex jaw joint and facial pain conditions from across Australia and overseas. The team also includes Dr Edward Nguyen and Dr Shreya Tocaciu.", "Dr Dimitroulis has been in specialist practice since 1995 and is a Consultant Maxillofacial Surgeon at St Vincent's Hospital Melbourne. He has extensive experience in treating patients who have had previous unsuccessful jaw or TMJ surgery, as well as those requiring total joint replacement. This practice is particularly valuable if your jaw problem is complicated by TMJ disease or previous surgery. You can learn more about related care on our <a href=\"/australia/tmj-treatment/\">TMJ disorders page</a>."]},
    {"rank": 10, "name": "Tasmanian Oral, Maxillofacial and Implant Surgery (TOMIS)", "location": "Hobart, TAS", "featured": False, "rating": "8.9/10", "pricing": "Medicare + private health insurance; typical total out-of-pocket $15,000\u2013$40,000", "hours": "Mon\u2013Fri 8:00am\u20135:00pm", "address": "30 Cascade Road, South Hobart TAS 7004", "phone": "(03) 6169 2129", "website": "https://tomis.com.au", "body": ["Tasmanian Oral, Maxillofacial and Implant Surgery (TOMIS) is the premier OMS provider in Tasmania, led by Dr Ankit Garg, FRACDS (OMS) FRCS(Ed), who is also the Head of Department for OMFS at Royal Hobart Hospital. Dr Garg is an Australian-trained and certified oral and maxillofacial surgeon with a Bachelor of Dental Surgery from Adelaide University and a Bachelor of Medicine and Surgery from the University of Melbourne.", "TOMIS offers a comprehensive range of procedures including jaw surgery (orthognathic), dental implants, wisdom teeth removal, sleep apnoea treatment (maxillomandibular advancement), and facial trauma management. The practice has locations in Hobart (30 Cascade Road) and Launceston (16 Canning Street). Because fewer specialist services exist in Tasmania, this practice plays a critical role in access to orthognathic care for Tasmanians who want to avoid interstate travel for major jaw surgery. See our <a href=\"/australia/hobart/\">Hobart dental guide</a> for additional local providers."]},
]

COST_HEADING = "Cost of Corrective Jaw Surgery in Australia"
COST = [
    "Corrective jaw surgery is a major procedure, and the total cost depends on the surgeon, hospital, anaesthetist, orthodontic treatment, and your private health insurance cover. In Australia, most patients have some costs covered by Medicare and private health insurance, but patients often face a significant out-of-pocket gap.",
    "<strong>Funding note:</strong> Medicare covers 75% of the MBS scheduled fee for orthognathic surgery (MBS item numbers 45617\u201345998). Private health insurance with top hospital cover is usually required to cover hospital and anaesthetist fees, and most major funds offer \u201cno gap\u201d or \u201cknown gap\u201d arrangements for eligible patients. Orthodontics is not covered by Medicare, although private health funds may provide a rebate of roughly $1,000\u2013$2,500. Always ask the surgeon\u2019s office for a written itemised quote before proceeding. For related cost information, see our <a href=\"/australia/oral-surgery/\">oral surgery guide</a>.",
]
COST_PRICES = [
    ("Orthodontics (pre & post)", "$5,000 \u2013 $10,000"),
    ("Total estimated cost", "$15,000 \u2013 $40,000+"),
]
COST_AFTER = [
    'See our <a href="/blog/">dental costs guide</a> for full fee breakdowns.',
]

CHOOSE_HEADING = "How to Choose a Corrective Jaw Surgery Provider in Australia"
CHOOSE_INTRO = "Ask these questions before you book."
CHOOSE_CRITERIA = [
    ("Are you a registered specialist oral and maxillofacial surgeon?", "Look for a surgeon with FRACDS (OMS) or equivalent specialist qualification, and membership with the Australian and New Zealand Association of Oral and Maxillofacial Surgeons (ANZAOMS)."),
    ("How many orthognathic cases do you perform each year?", "High-volume surgeons tend to have better outcomes and lower complication rates. Ask for their experience with your specific jaw deformity."),
    ("What exactly does the quoted fee include?", "A comprehensive quote should include the surgeon\u2019s fee, anaesthetist\u2019s fee, hospital fee, initial consultations, and follow-up appointments. Ask what is not included."),
    ("Do you work closely with my orthodontist?", "Corrective jaw surgery almost always requires braces before and after surgery. A good surgeon will coordinate closely with your orthodontist to plan the entire treatment timeline."),
    ("What are the risks, and how do you manage complications?", "Your surgeon should clearly explain the risk of nerve damage, infection, relapse, and non-union, and how they manage these if they occur. Use our <a href=\"/australia/\">Australian dentist directory</a> to find qualified specialists, or explore related services like <a href=\"/australia/orthodontist/\">orthodontics</a> and <a href=\"/australia/sleep-apnoea-treatment/\">sleep apnoea treatment</a>."),
]
CHOOSE_AFTER = []

METHODOLOGY_HEADING = "Methodology: How We Ranked These Clinics"
METHODOLOGY = [
    "We ranked these clinics using the criteria below."
]
METHODOLOGY_CRITERIA = [
    "We ranked each practice using 8 criteria:",
    "Specialist qualifications \u2014 verification of FRACDS (OMS) or equivalent and ANZAOMS membership.",
    "Orthognathic surgery volume \u2014 the number of corrective jaw cases performed regularly by the practice.",
    "Scope of procedures \u2014 including maxillary osteotomy, BSSO, bimaxillary osteotomy, genioplasty, and segmental osteotomy.",
    "Multidisciplinary care \u2014 coordination with orthodontists, physiotherapists, speech pathologists, and sleep physicians.",
    "Hospital and facility access \u2014 private hospital admission and modern theatre facilities.",
    "Patient support and follow-up \u2014 clear pre-operative planning, post-operative reviews, and emergency access.",
    "Accessibility and location \u2014 availability of multiple consulting rooms or regional coverage.",
    "Fee transparency \u2014 willingness to provide itemised quotes and insurance information.",
    "These criteria are designed to give a balanced view of clinical excellence and patient experience. Rankings may change over time as practices update their services and staff.",
]
METHODOLOGY_AFTER = []

FAQ_HEADING = "Frequently Asked Questions"
FAQS = [
    ("Does Medicare cover corrective jaw surgery?", "Yes, Medicare covers 75% of the MBS scheduled fee for the surgeon. Hospital and anaesthetist fees are usually covered by private health insurance if you have top hospital cover. Orthodontics is not covered by Medicare, but health funds may pay a rebate. Explore our <a href=\"/australia/\">Australia dental hub</a> for more information on Medicare and dental coverage."),
    ("Do I need braces before and after jaw surgery?", "Yes, almost all patients need orthodontic treatment before and after corrective jaw surgery. Braces align the teeth to the new jaw position over 12\u201318 months before surgery and 6\u201312 months after surgery. Learn more about the orthodontic process on our <a href=\"/australia/orthodontist/\">orthodontics page</a>."),
    ("How long is the recovery time for jaw surgery?", "Most patients take 2\u20134 weeks off work or school, follow a soft diet for about 6 weeks, and see most swelling resolve within 3 months. Full bone healing takes around 12 months. Recovery times vary depending on the complexity of the procedure. For a broader look at recovery, see our <a href=\"/australia/oral-surgery/\">oral surgery guide</a>."),
    ("What are the risks of corrective jaw surgery?", "The main risks include temporary or permanent nerve damage, infection, bleeding, relapse, non-union of the bone, and complications from general anaesthetic. The chance of permanent significant numbness in the lower lip or chin is around 1\u20132%. Your surgeon will discuss these risks in detail during your consultation. Review our <a href=\"/australia/\">Australia dental hub</a> for more information on surgical risks."),
    ("Can I get jaw surgery for sleep apnoea?", "Yes. Maxillomandibular advancement (MMA) is a highly effective surgical treatment for moderate to severe obstructive sleep apnoea when CPAP therapy has failed or is not tolerated. A surgeon will assess your airway and jaw position to decide if MMA is appropriate. See our <a href=\"/australia/sleep-apnoea-treatment/\">sleep apnoea treatment page</a> for more details."),
    ("What is the best age for jaw surgery?", "Most patients are between 18 and 40 years old, after the jaw has stopped growing \u2014 around 16 for females and 18 for males. Older adults can also have corrective jaw surgery, but healing and recovery may take longer. Read more about treatment timing in our <a href=\"/australia/orthodontist/\">orthodontics guide</a>."),
    ("How do I find a qualified surgeon for corrective jaw surgery in Australia?", "Look for a registered specialist oral and maxillofacial surgeon with FRACDS (OMS) or equivalent qualification and membership with ANZAOMS. You can also use the <a href=\"/australia/\">Australian dentist directory</a> to find experienced providers near you."),
]

CTA_TITLE = "Are you a Corrective Jaw Surgery provider in Australia?"
CTA_TEXT = "Apply to be featured in our next update."

DISCLOSURE = "Practices in positions 1 to 3 are paid placements with do-follow links. Practices in positions 4 to 10 are listed editorially with no-follow links. Paid placement never affects positions 4 to 10."

SCHEMAS = []  # built by the template's _build_schemas() in manual workflow
