"""Content for /australia/dental-sealants/ — Top 10 Dental Sealants in Australia.
Generated by service_pipeline.py (2026-08-29)."""
import json

META_TITLE = "Top 10 Dental Sealants in Australia"
META_DESC = "Compare the top 10 dental sealants in Australia."
H1 = "Top 10 Dental Sealants in Australia"
BADGE = "Top 10 — Reviewed & Ranked"

INTRO = [
    "Dental sealants — also called fissure sealants — are thin protective coatings painted onto the chewing surfaces of back teeth to stop food and bacteria from settling in deep pits and fissures. In Australia, <a href=\"/blog/conditions/tooth-decay/\">tooth decay</a> remains the most common chronic disease among children: around one-third of children have decay in their baby teeth by age five, and decay in permanent teeth rises sharply in the early teenage years — exactly when the first and second permanent molars erupt.",
    "This guide reviews Australia's 10 leading dental sealant providers, explains how sealants work, who needs them, and what they cost under the Child Dental Benefits Schedule (CDBS), private health insurance, and public school dental services.",
    'Positions 1 to 3 are paid placements with do-follow links. Positions 4 to 10 are editorial selections with no-follow links. Browse our complete directory of <a href="/australia/">all dental services across Australia</a>. Read <a href="/methodology/">our methodology</a> and our <a href="/disclosures/">disclosures policy</a> for full transparency.',
]

WHEN_HEADING = "When Do You Need Dental Sealants?"
WHEN = [
    "This page is for you if you are a parent of a child aged 6–13. First permanent molars erupt at around age 6, and second molars at around age 11–13. These are the ideal sealant windows. <a href=\"/australia/childrens-dentist/\">Children's dentistry</a> providers across Australia recommend sealants within months of eruption to prevent decay before it starts. If decay is left untreated in these newly erupted molars, it can reach the pulp and require <a href=\"/australia/root-canal-treatment/\">root canal treatment</a> — a far more invasive and expensive procedure than a simple sealant.",
    "Adults with deep pits and fissures and no existing fillings or decay in their molars can also benefit. Sealants are not just for kids. High-caries-risk patients — those with past decay, poor diet, orthodontic appliances, dry mouth, or special health needs — are strong candidates regardless of age.",
]

WHEN_ALERT = "If you have severe pain, uncontrolled bleeding, or facial swelling that affects breathing or vision, call 000 or go to the nearest hospital emergency department immediately."

WHO_HEADING = "Which are the top 10 dental sealants in Australia?"
WHO_TOP10 = "The ten clinics below are ranked from 1 to 10. Ranks 1-3 are featured entries."

TOP10 = [
    {"rank": 1, "name": "Smile Solutions", "location": "Melbourne CBD, VIC ", "featured": True, "rating": "4.9/5 (Google)", "pricing": "From $65 per tooth", "hours": "Mon\u2013Fri 8:00am\u20136:00pm, Sat 8:30am\u20134:30pm", "address": "Level 1, 220 Collins Street, Manchester Unity Building, Melbourne VIC 3000", "phone": "(03) 9650 4920", "website": "https://www.smilesolutions.com.au", "body": ["Smile Solutions is one of Melbourne's largest specialist-group dental practices, housing prosthodontists, periodontists, endodontists, and oral surgeons under one roof. The Collins Street practice is known for complex restorative work, full-mouth rehabilitation, and sedation and sleep dentistry \u2014 making it a strong option for anxious children who need preventive treatment. Fissure sealants are delivered as part of a broader preventive care program for children and high-caries-risk adults.", "<strong>Why it\u2019s featured:</strong> Specialist-led multidisciplinary care in a premium CBD location, with sedation options for nervous patients."]},
    {"rank": 2, "name": "Macquarie Street Dental", "location": "Sydney CBD, NSW ", "featured": True, "rating": "4.8/5 (Google)", "pricing": "$55\u2013$75 per tooth", "hours": "Mon\u2013Fri 8:00am\u20135:30pm", "address": "Level 4, 135 Macquarie Street, Sydney NSW 2000", "phone": "(02) 9251 5999", "website": "https://www.macquariestreetdental.com.au", "body": ["Overlooking the Royal Botanic Garden, Macquarie Street Dental is an established CBD practice with a strong preventive focus. The team provides fissure sealants and <a href=\"/australia/fluoride-treatment/\">fluoride varnish</a> as part of structured child dental programs, alongside general and cosmetic dentistry enhanced by digital scanning and imaging. Its central location and extended weekday hours suit busy Sydney families.", "<strong>Why it\u2019s featured:</strong> Established CBD practice with a structured preventive program for children and digital dentistry workflows."]},
    {"rank": 3, "name": "Mosman Dental Surgery", "location": "Lower North Shore, Sydney NSW ", "featured": True, "rating": "4.9/5 (Google)", "pricing": "$55\u2013$65 per tooth", "hours": "Mon\u2013Fri 8:30am\u20135:00pm, Sat 9:00am\u20131:00pm", "address": "Suite 1D, 1 Spit Road, Mosman NSW 2088", "phone": "(02) 9969 7433", "website": "https://www.mosmandentalsurgery.com.au", "body": ["A long-running Lower North Shore family practice, Mosman Dental Surgery has built its reputation on gentle family dentistry and preventive recalls. Sealant placement on newly erupted molars is a core part of their children\u2019s care pathway, delivered with a calm, child-friendly approach that local parents consistently praise. Preventive appointments are unhurried, and the team explains every step to both parent and child.", "<strong>Why it\u2019s featured:</strong> Outstanding patient ratings and a dedicated family-focused approach to preventive dentistry."]},
    {"rank": 4, "name": "Maven Dental Maroubra", "location": "Maroubra, Sydney NSW ", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Bulk-billed for CDBS-eligible children; private from $50 per tooth", "hours": "Mon\u2013Fri 8:30am\u20136:00pm, Sat 9:00am\u20131:00pm", "address": "254 Maroubra Road, Maroubra NSW 2035", "phone": "(02) 9349 7777", "website": "https://www.mavendental.com.au", "body": ["Maven Dental Maroubra is part of the Maven Dental group, one of Australia\u2019s largest dental networks, giving patients access to group-wide quality standards and modern equipment. The Maroubra surgery offers bulk-billed check-ups for eligible patients, children\u2019s dentistry, and preventive care including fissure sealants. Suburban families appreciate the convenient hours and straightforward CDBS claiming."]},
    {"rank": 5, "name": "Dental on Clarendon", "location": "South Melbourne VIC ", "featured": False, "rating": "4.8/5 (Google)", "pricing": "No-gap on CDBS child check-ups; private from $55 per tooth", "hours": "Mon\u2013Fri 8:30am\u20135:30pm, Sat 9:00am\u20131:00pm", "address": "383 Clarendon Street, South Melbourne VIC 3205", "phone": "(03) 9690 3285", "website": "https://www.dentalonclarendon.com.au", "body": ["An established South Melbourne practice with a focus on family and cosmetic dentistry, Dental on Clarendon is popular with local parents for no-gap child check-ups on the CDBS. Sealants are offered as part of a gentle preventive care pathway, and the team is experienced at putting young patients at ease. The central South Melbourne location is easy to reach from the CBD and inner suburbs."]},
    {"rank": 6, "name": "Better Smiles Bondi Junction", "location": "Bondi Junction, Sydney NSW ", "featured": False, "rating": "5.0/5 (Google)", "pricing": "$55\u2013$75 per tooth", "hours": "Mon\u2013Fri 8:30am\u20135:30pm, Sat 9:00am\u20131:00pm", "address": "503/3 Waverley Street, Bondi Junction NSW 2022", "phone": "(02) 9387 1032", "website": "https://www.bsmilesbondijunction.com.au", "body": ["Better Smiles Bondi Junction is a full-service family dental clinic offering comprehensive care for all ages, from routine check-ups to advanced restorative and cosmetic treatments. The practice combines modern technology with personalised care, and its family focus makes it a reliable choice for children\u2019s preventive dentistry including fissure sealants.", "<strong>Why it\u2019s featured:</strong> Family-oriented practice with bulk-billed CDBS claiming and a gentle, child-friendly approach."]},
    {"rank": 7, "name": "Precision Dental", "location": "Toowong, Brisbane QLD ", "featured": False, "rating": "4.9/5 (Google)", "pricing": "$50\u2013$70 per tooth", "hours": "Mon\u2013Fri 8:30am\u20135:30pm, Sat 8:30am\u201312:30pm", "address": "33 Sherwood Road, Toowong QLD 4066", "phone": "(07) 3870 3519", "website": "https://www.precisiondental.com.au", "body": ["Precision Dental is a Brisbane general practice with a strong family and children\u2019s focus, offering fissure sealants, fluoride treatment, and preventive care as part of structured child dental plans. The practice is particularly well reviewed by parents of anxious children, with a gentle, explanatory approach that reduces dental fear early. The convenient Toowong location is close to the CBD and public transport."]},
    {"rank": 8, "name": "MGA Dental", "location": "Surfers Paradise, Gold Coast QLD ", "featured": False, "rating": "4.8/5 (Google)", "pricing": "$55\u2013$75 per tooth", "hours": "Mon\u2013Fri 8:30am\u20135:30pm, Sat 9:00am\u20131:00pm", "address": "122 Salerno Street, Surfers Paradise QLD 4217", "phone": "(07) 5539 9748", "website": "https://www.mgadental.com.au", "body": ["MGA Dental is an established Gold Coast group known for dental implants, CEREC same-day crowns, and comprehensive family and preventive dentistry. The practice is active in community children\u2019s oral-health events and offers sealants as part of a broader child dental health program. Same-day digital dentistry means fewer appointments for busy Gold Coast families."]},
    {"rank": 9, "name": "Adelaide DentalCare", "location": "Adelaide CBD, SA ", "featured": False, "rating": "4.8/5 (Google)", "pricing": "$50\u2013$65 per tooth", "hours": "Mon\u2013Fri 8:30am\u20135:30pm", "address": "Level 1, 45 Grenfell Street, Adelaide SA 5000", "phone": "(08) 8212 5976", "website": "https://www.adelaidedentalcare.com.au", "body": ["Adelaide DentalCare is a centrally located city practice offering general, preventive and family dentistry for patients of all ages. The Grenfell Street clinic provides fissure sealants, fluoride varnish, check-ups and cleans, and is well set up for families with children, providing bulk-billed CDBS-eligible care and a friendly, low-stress environment."]},
    {"rank": 10, "name": "CBD Dental Perth", "location": "Perth CBD, WA ", "featured": False, "rating": "4.7/5 (Google)", "pricing": "$55\u2013$70 per tooth", "hours": "Mon\u2013Fri 8:00am\u20137:00pm, Sat 8:00am\u20135:00pm", "address": "Level 8, 68 St Georges Terrace, Perth WA 6000", "phone": "(08) 9321 1800", "website": "https://www.cbddentalperth.com", "body": ["CBD Dental Perth is a modern city practice combining general, family, cosmetic and implant dentistry with a strong preventive focus. Located conveniently at Exchange House on St Georges Terrace, the practice offers extended hours including Saturday, making it easy for Perth families to schedule sealant appointments for their children without disrupting school or work."]},
]

COST_HEADING = "How Much Do Dental Sealants Cost in Australia?"
COST = [
    "Sealant fees vary by state, practice type, and whether you use Medicare (CDBS), private health insurance, or public school dental services. The Australian Dental Association item number for a fissure sealant is <strong>611</strong>, and most Australian dentists charge between $40 and $90 per tooth.",
    "The Child Dental Benefits Schedule provides up to approximately $1,026 per child over two consecutive calendar years (indexed annually — verify the current cap with Services Australia at time of writing). Most practices bulk-bill sealants for CDBS-eligible children with no out-of-pocket gap. Private health insurance typically applies a 2-month waiting period for extras. State school dental services (QLD, NSW, SA, WA, VIC and others) offer free or subsidised dental sealants for school-age children.",
]
COST_PRICES = [
    ("Fissure sealant per tooth (private, no insurance)", "$40 – $90 (commonly $55 – $75)"),
    ("Repair or re-application of a lost sealant", "$30 – $60 per tooth"),
    ("Comprehensive exam plus one sealant (new patient)", "$150 – $250 (varies by practice)"),
]
COST_AFTER = [
    'See our <a href="/blog/">dental costs guide</a> for full fee breakdowns.',
]

CHOOSE_HEADING = "How to Choose a Dental Sealant Provider"
CHOOSE_INTRO = "Ask these questions before you book."
CHOOSE_CRITERIA = [
    ("Question", "<strong>Do they bulk-bill the CDBS?</strong> If your child is aged 2–17 and eligible, choosing a practice that bulk-bills item 611 means zero out-of-pocket cost."),
    ("Question", "<strong>Are they experienced with anxious children?</strong> Sealant placement is quick and painless, but a child-friendly dentist makes the experience far easier. Look for practices that advertise <a href=\"/australia/childrens-dentist/\">children's dentistry</a>."),
    ("Question", "<strong>Which sealant material do they use?</strong> Resin-based composite sealants are the most durable; glass ionomer (GIC) releases fluoride and suits partly erupted teeth. Ask which they recommend for your child."),
    ("Question", "<strong>Do they offer a structured preventive program?</strong> The best practices combine sealants with fluoride varnish, recall appointments, and dietary advice — not just a one-off procedure."),
    ("Question", "<strong>Is the location and appointment availability practical?</strong> Consider opening hours, parking, public transport, and whether the practice can see siblings together."),
]
CHOOSE_AFTER = []

METHODOLOGY_HEADING = "How We Ranked Australia's Top Dental Sealant Providers"
METHODOLOGY = [
    "We ranked these clinics using the criteria below."
]
METHODOLOGY_CRITERIA = [
    "To build this list, we evaluated clinics against eight criteria:",
    "Verified contact details — address and phone confirmed against the practice's official website and Google Business Profile.",
    "Preventive service range — fissure sealants, fluoride varnish, and child dental programs.",
    "Paediatric and family dentistry experience — evidence of child-focused care pathways.",
    "Patient ratings — Google and trusted directory scores at time of research.",
    "Pricing transparency — published fees, CDBS bulk-billing, and no-gap options.",
    "Clinical scope — availability of specialists or advanced training relevant to restorative outcomes.",
    "Practice longevity — established reputation (10+ years operating where verifiable).",
    "Accessibility — location, hours, parking, and public transport access.",
    "Note: All details were re-verified against live practice websites before publication; phone numbers and addresses change with relocations. If you spot an error, contact us so we can update the page.",
]
METHODOLOGY_AFTER = []

FAQ_HEADING = "Frequently Asked Questions"
FAQS = [
    ("At what age should children get dental sealants?", "First permanent molars erupt at around age 6, and second molars at around age 11–13. Sealants are most effective when placed shortly after eruption, before decay can develop in the new grooves. Read more about child dental health."),
    ("Do dental sealants hurt? Do they involve drilling?", "No. On a decay-free tooth, sealant placement needs no needle and no drilling — just a clean, etch, rinse, and light-cure. Each tooth takes roughly five to ten minutes."),
    ("How long do dental sealants last?", "Resin-based sealants typically last three to five years, and often longer. The dentist checks sealant retention at routine appointments and can repair or re-apply a sealant if it chips or wears."),
    ("Are dental sealants covered by Medicare or private health insurance?", "The CDBS covers sealants for eligible children aged 2–17 (cap approximately $1,026 per child over two calendar years, indexed annually). Private extras policies typically cover 60–85% of the fee. Ask your dentist about <a href=\"/australia/dental-check-up/\">dental check-up</a> coverage."),
    ("Can adults get dental sealants?", "Yes. Adults with deep pits and fissures and no existing fillings or decay in those teeth are candidates — especially anyone at high risk of caries."),
    ("What is the difference between dental sealants and fluoride varnish?", "<a href=\"/australia/fluoride-treatment/\">Fluoride varnish</a> strengthens tooth enamel; sealants physically seal off the grooves. They are complementary — varnish protects the smooth surfaces, sealants protect the biting surfaces."),
    ("What happens if a sealant chips or falls off?", "A damaged sealant can usually be repaired, and a lost one is easily replaced after the tooth is cleaned and re-etched. The tooth is no worse off, but it should be examined promptly."),
]

CTA_TITLE = "Are you a Dental Sealants provider in Australia?"
CTA_TEXT = "Apply to be featured in our next update."

DISCLOSURE = "Practices in positions 1 to 3 are paid placements with do-follow links. Practices in positions 4 to 10 are listed editorially with no-follow links. Paid placement never affects positions 4 to 10."

SCHEMAS = []  # built by the template's _build_schemas() in manual workflow