"""Content for /australia/general-dentistry/ — Top 10 General Dentistry in Australia.
Generated by service_pipeline.py (2026-08-29). Manually corrected with verified clinic data (2026-08-30)."""
import json

META_TITLE = "Top 10 General Dentists in Australia"
META_DESC = "Compare the top 10 general dentistry clinics in Australia."
H1 = "Top 10 General Dentistry in Australia"
BADGE = "Top 10 — Reviewed & Ranked"

INTRO = [
    "Finding a reliable general dentist in Australia shouldn't require a root canal of research. Whether you are searching for a family practice in the suburbs or a convenient city clinic near your office, the choice of dentist shapes your long-term oral health more than any single treatment. General dentistry is the foundation of everything — routine check-ups, cleans, fillings, gum care and early diagnosis that stops small problems becoming expensive ones.",
    "This ranking focuses on clinics across Australia's major cities, from Sydney and Melbourne to Brisbane, Perth and Adelaide. Every clinic below was checked against its official website, contact details and service list during research. Alongside the rankings, you will find typical private fees for check-ups, cleans, fillings, extractions, root canals and crowns, a step-by-step guide to choosing the right dentist, and answers to the most common questions Australians ask before booking.",
    'Positions 1 to 3 are paid placements with do-follow links. Positions 4 to 10 are editorial selections with no-follow links. Browse our complete directory of <a href="/australia/">all dental services across Australia</a>. Read <a href="/methodology/">our methodology</a> and our <a href="/disclosures/">disclosures policy</a> for full transparency.',
]

WHEN_HEADING = "When do you need a general dentist?"
WHEN = [
    "You should see a general dentist for routine check-ups and cleans every 6 to 12 months, or sooner if you experience tooth pain, bleeding gums, sensitivity, visible decay or damage to a tooth. General dentistry covers preventive care, diagnosis and treatment of common dental conditions, and referral to specialists when needed.",
    "<strong>Emergency alert:</strong> If you have severe toothache, facial swelling, uncontrolled bleeding or trauma to the teeth, see a dentist urgently or present to a hospital emergency department.",
]

WHEN_ALERT = "If you have severe pain, uncontrolled bleeding, or facial swelling that affects breathing or vision, call 000 or go to the nearest hospital emergency department immediately."

WHO_HEADING = "Which are the top 10 general dentistry clinics in Australia?"
WHO_TOP10 = "The ten clinics below are ranked from 1 to 10. Ranks 1-3 are featured entries."

TOP10 = [
    {"rank": 1, "name": "Smile Solutions", "location": "Melbourne CBD, VIC", "featured": True, "rating": "4.8/5 (Google)", "pricing": "Check-up $95–$150", "hours": "Mon–Fri 8:00am–6:00pm, Sat 9:00am–5:00pm", "address": "Level 1, 220 Collins St, Manchester Unity Building, Melbourne VIC 3000", "phone": "(03) 9650 4920", "website": "https://www.smilesolutions.com.au", "body": ["Smile Solutions is one of Melbourne's largest and most comprehensive dental practices, housing multiple specialists under one roof in the iconic Manchester Unity Building. Their general dentistry team provides routine check-ups, cleans, fillings, gum care and preventive treatment, with the ability to refer patients to in-house specialists for orthodontics, implants, periodontics and oral surgery without leaving the building.", "The practice is known for its high standards of care, modern technology and patient-centred approach. Open six days a week with easy access from Flinders Street Station and all CBD tram stops."]},
    {"rank": 2, "name": "Macquarie Street Dental", "location": "Sydney CBD, NSW", "featured": True, "rating": "4.7/5 (Google)", "pricing": "Check-up $95–$140", "hours": "Mon–Fri 8:30am–5:00pm", "address": "Level 4, 135 Macquarie St, Sydney NSW 2000", "phone": "(02) 9251 5999", "website": "https://www.macquariestreetdental.com.au", "body": ["Macquarie Street Dental is a well-established practice in Sydney's premier medical precinct, offering comprehensive general dentistry for patients across the CBD and eastern suburbs. The team provides routine check-ups, scale and cleans, fillings, crowns, bridges, root canal therapy and preventive care in a professional and comfortable setting.", "Located on Macquarie Street near Martin Place and St James stations, the practice is easily accessible by train and bus. The team is known for its meticulous approach and long-term patient relationships."]},
    {"rank": 3, "name": "Mosman Dental Surgery", "location": "Mosman, NSW", "featured": True, "rating": "4.9/5 (Google)", "pricing": "Check-up $85–$130", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "Suite 1D, 1 Spit Rd, Mosman NSW 2088", "phone": "(02) 9969 7433", "website": "https://www.mosmandentalsurgery.com.au", "body": ["Mosman Dental Surgery is a family-owned practice on Sydney's lower north shore, providing comprehensive general dentistry for patients of all ages. The experienced team offers routine check-ups, professional cleans, fillings, preventive care, cosmetic dentistry and children's dentistry in a relaxed, patient-focused environment.", "The practice is located on Spit Road in the heart of Mosman, with convenient parking and public transport options. Known for their gentle approach and high-quality care, the team has built a loyal patient base over many years."]},
    {"rank": 4, "name": "Maven Dental Maroubra", "location": "Maroubra, NSW", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Check-up $80–$120", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "254 Maroubra Rd, Maroubra NSW 2035", "phone": "(02) 9349 7777", "website": "https://www.mavendental.com.au", "body": ["Maven Dental Maroubra is part of Australia's largest network of independent dental practices, offering high-quality general dentistry in Sydney's eastern suburbs. The practice provides routine check-ups, scale and cleans, fillings, root canal therapy, crowns, bridges and preventive care with a focus on gentle, evidence-based treatment.", "The clinic is conveniently located on Maroubra Road with on-site parking and is open six days a week. They accept all major health funds and offer on-the-spot rebates via HICAPS."]},
    {"rank": 5, "name": "Dental on Clarendon", "location": "South Melbourne, VIC", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Check-up $85–$130", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "383 Clarendon St, South Melbourne VIC 3205", "phone": "(03) 9690 3285", "website": "https://www.dentalonclarendon.com.au", "body": ["Dental on Clarendon is a modern family practice in South Melbourne offering comprehensive general dentistry for patients of all ages. The experienced team provides routine check-ups, professional cleans, white fillings, crowns, bridges, root canal therapy and children's dentistry in a comfortable, modern setting.", "Conveniently located on Clarendon Street with tram access and nearby parking, the practice is a popular choice for South Melbourne, Albert Park and Port Melbourne residents. They are a preferred provider for major health funds."]},
    {"rank": 6, "name": "Better Smiles Bondi Junction", "location": "Bondi Junction, NSW", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Check-up $90–$140", "hours": "Mon–Fri 9:00am–5:30pm, Sat 9:00am–1:00pm", "address": "503/3 Waverley St, Bondi Junction NSW 2022", "phone": "(02) 9387 1032", "website": "https://www.bsmilesbondijunction.com.au", "body": ["Better Smiles Bondi Junction is a modern dental practice in Sydney's eastern suburbs, providing comprehensive general dentistry in a patient-centred environment. The team offers routine check-ups, professional cleans, fillings, cosmetic dentistry, orthodontics and preventive care using the latest technology.", "Located in the heart of Bondi Junction, the practice is a short walk from Bondi Junction station and the Westfield shopping centre. They offer flexible appointment times and direct health fund claiming."]},
    {"rank": 7, "name": "Precision Dental", "location": "Toowong, QLD", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Check-up $85–$130", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "33 Sherwood Rd, Toowong QLD 4066", "phone": "(07) 3870 3519", "website": "https://www.precisiondental.com.au", "body": ["Precision Dental is a well-regarded family practice in Toowong, Brisbane, offering comprehensive general dentistry for patients of all ages. The experienced team provides routine check-ups, scale and cleans, fillings, crowns, bridges, root canal therapy, cosmetic dentistry and children's dentistry.", "Conveniently located on Sherwood Road near Toowong Village, the practice is easily accessible by train, bus and car. They are known for their gentle approach and transparent pricing."]},
    {"rank": 8, "name": "MGA Dental", "location": "Surfers Paradise, QLD", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Check-up $80–$120", "hours": "Mon–Fri 9:00am–5:30pm, Sat 9:00am–1:00pm", "address": "122 Salerno St, Surfers Paradise QLD 4217", "phone": "(07) 5539 9748", "website": "https://www.mgadental.com.au", "body": ["MGA Dental is a modern Gold Coast practice offering comprehensive general dentistry for residents and visitors to Surfers Paradise. The clinical team provides routine check-ups, professional cleans, fillings, cosmetic dentistry, root canal therapy and preventive care in a modern, patient-friendly environment.", "Located on Salerno Street in the heart of Surfers Paradise, the practice is easily accessible from the Gold Coast Highway. They offer flexible payment options and accept all major health funds."]},
    {"rank": 9, "name": "Adelaide DentalCare", "location": "Adelaide CBD, SA", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Check-up $80–$120", "hours": "Mon–Fri 8:30am–5:30pm", "address": "Level 1, 45 Grenfell St, Adelaide SA 5000", "phone": "(08) 8212 5976", "website": "https://www.adelaidedentalcare.com.au", "body": ["Adelaide DentalCare is a modern city practice in the heart of the Adelaide CBD, offering comprehensive general dentistry for patients across South Australia. The team provides routine check-ups, scale and cleans, fillings, crowns, bridges, root canal therapy, cosmetic dentistry and preventive care.", "Conveniently located on Grenfell Street with easy access from public transport, the practice is a popular choice for city workers and Adelaide residents. They offer on-the-spot health fund claims and flexible appointment times."]},
    {"rank": 10, "name": "CBD Dental Perth", "location": "Perth CBD, WA", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Check-up $85–$130", "hours": "Mon–Fri 8:30am–5:30pm", "address": "Level 8, 68 St Georges Tce, Perth WA 6000", "phone": "(08) 9321 1800", "website": "https://www.cbddentalperth.com", "body": ["CBD Dental Perth is a modern city practice located on St Georges Terrace in the Perth CBD, providing comprehensive general dentistry for patients across Western Australia. The experienced team offers routine check-ups, professional cleans, fillings, crowns, bridges, root canal therapy, cosmetic dentistry and preventive care.", "With stunning views of the Swan River, the practice creates a relaxing environment for patients. Located in the heart of Perth's financial district with easy access from the Elizabeth Quay train station and all CBD bus routes."]},
]

COST_HEADING = "What does general dentistry cost in Australia?"
COST = [
    "Private dental fees in Australia vary by city, suburb, practitioner and treatment complexity. The ranges below reflect typical private fees without private health insurance, based on Australian Dental Association fee data, state dental fee guides and clinic published schedules. Always ask for a written itemised quote before treatment begins.",
    "The table below lists typical Australian out-of-pocket costs for common general dentistry procedures.",
]
COST_PRICES = [
    ("Check-up and clean", "$50 – $300"),
    ("Fillings (composite resin, per tooth)", "$150 – $350"),
    ("Simple extraction (per tooth)", "$180 – $380"),
    ("Root canal therapy (molar)", "$1,200 – $2,200"),
    ("Crown (porcelain fused to metal)", "$1,200 – $2,000"),
    ("Denture (full upper or lower)", "$1,500 – $3,500"),
]
COST_AFTER = [
    'See our <a href="/blog/">dental costs guide</a> for full fee breakdowns.',
]

CHOOSE_HEADING = "How to choose a general dentist in Australia"
CHOOSE_INTRO = "Ask these questions before you book."
CHOOSE_CRITERIA = [
    ("What is the practice's location and are they open when you need them?", "Choose a clinic that is convenient to your home or workplace and has hours that suit your schedule. Weekend and evening availability can make a significant difference for regular preventive visits."),
    ("Does the practice accept your health fund and offer on-the-spot claiming?", "Most private health funds offer preferred provider networks. Check whether the practice is a preferred provider for your fund and whether they offer HICAPS on-the-spot claiming to reduce out-of-pocket costs on the day."),
    ("What range of services do they offer in-house?", "Practices that offer a wide range of services (fillings, crowns, root canals, cosmetic dentistry, children's dentistry) can manage your ongoing care without multiple referrals. Some practices also have visiting specialists for implants or orthodontics."),
    ("Do they have experience with nervous patients or offer sedation options?", "If you experience dental anxiety, look for a practice that offers happy gas, oral sedation or sleep dentistry options. Many general dentists have training in patient comfort and anxiety management."),
    ("Are fees transparent and do they provide itemised quotes?", "A good general dentist will provide a written treatment plan with itemised costs before any procedure begins. Avoid practices that are reluctant to provide a written quote."),
]
CHOOSE_AFTER = []

METHODOLOGY_HEADING = "How we ranked the top 10 general dentistry clinics"
METHODOLOGY = [
    "We ranked these clinics using the criteria below."
]
METHODOLOGY_CRITERIA = [
    "Every clinic in this ranking was assessed against the same 8 criteria. Points were weighted towards verified data and patient value.",
    "Verified contact details — Practices with a confirmed full street address and live phone number scored highest.",
    "Range of general dentistry services — Whether the clinic offers routine check-ups, cleans, fillings, crowns, bridges, root canals, extractions and preventive care.",
    "Patient reviews and reputation — Quality and volume of Google and practice-published patient reviews.",
    "Pricing transparency — Published fee schedules, live price lists or clear quotes before booking.",
    "Location accessibility — CBD access, public transport, parking and suitability for families or workers.",
    "Health fund and HICAPS processing — On-the-spot rebates, gap-free offers and preferred provider arrangements.",
    "Children's dentistry and family care — Whether the practice welcomes patients of all ages and offers paediatric-friendly care.",
    "Technology and comfort — Modern equipment, digital X-rays, sedation options and patient comfort amenities.",
]
METHODOLOGY_AFTER = []

FAQ_HEADING = "Frequently Asked Questions"
FAQS = [
    ("How much does a general dentistry check-up cost in Australia?", "A standard check-up with a scale and clean typically costs between $80 and $200 without private health insurance. With most extras policies, you can expect a rebate of 60–80% of the cost. Many practices offer gap-free check-ups for preferred health fund members."),
    ("How often should I see a general dentist?", "The Australian Dental Association recommends a check-up and clean every 6 to 12 months for most people. Your dentist may recommend more frequent visits if you have a history of gum disease, frequent cavities, or other risk factors such as smoking, diabetes or dry mouth."),
    ("Does Medicare cover general dentistry for adults?", "Medicare does not cover routine dental check-ups, cleans, fillings or most other general dentistry procedures for adults. Some chronic disease management plans may provide limited dental benefits. Eligible children aged 2–17 can access the Child Dental Benefits Schedule (CDBS) for up to $1,013 over 2 calendar years."),
    ("What is the difference between a general dentist and a specialist?", "A general dentist provides routine preventive care, diagnosis and treatment of common dental conditions. A specialist (such as an orthodontist, periodontist or oral surgeon) has completed additional years of training in a specific area. Your general dentist will refer you to a specialist when your needs go beyond their scope of practice."),
    ("Can I see a general dentist for cosmetic dentistry?", "Many general dentists offer cosmetic procedures such as teeth whitening, composite bonding and porcelain veneers. For complex cosmetic cases, your general dentist may work with or refer to a cosmetic dentistry specialist. It is worth asking about cosmetic options during your routine check-up."),
    ("What should I bring to my first appointment?", "Bring your Medicare card, private health insurance details, a list of any medications you are taking, and any previous dental X-rays or records if available. Arrive 10–15 minutes early to complete the new patient registration forms."),
]

CTA_TITLE = "Are you a General Dentistry provider in Australia?"
CTA_TEXT = "Apply to be featured in our next update."

DISCLOSURE = "Practices in positions 1 to 3 are paid placements with do-follow links. Practices in positions 4 to 10 are listed editorially with no-follow links. Paid placement never affects positions 4 to 10."

SCHEMAS = []  # built by the template's _build_schemas() in manual workflow