"""Content for /australia/inlays-and-onlays/ — Top 10 Inlays and Onlays in Australia.
Generated by service_pipeline.py (2026-08-30)."""
import json

META_TITLE = "Top 10 Inlays and Onlays in Australia: Reviewed & Ranked"
META_DESC = "Compare the top 10 inlays and onlays in Australia."
H1 = "Top 10 Inlays and Onlays in Australia"
BADGE = "Top 10 — Reviewed & Ranked"

INTRO = [
    "Inlays and onlays are <strong>the gold standard for repairing damaged teeth</strong>. Unlike direct fillings, these custom-made indirect restorations are fabricated in a dental laboratory and bonded to the tooth, providing exceptional fit, strength, and longevity. For Australian adults researching tooth repair options, understanding the difference between inlays, onlays, and crowns is the first step toward a confident, healthy smile. This guide compares inlays and onlays Australia-wide and ranks the top 10 clinics so you can make an informed decision.",
    "This guide presents the top 10 dentists in Australia for inlays and onlays, with a focus on verified clinics in Sydney and Melbourne. Whether you need a porcelain inlay for a premolar or an onlay to cover a damaged cusp, this list narrows your search. Each clinic is evaluated on service offerings, geographic convenience, and online presence.",
    'Positions 1 to 3 are paid placements with do-follow links. Positions 4 to 10 are editorial selections with no-follow links. Browse our complete directory of <a href="/australia/">all dental services across Australia</a>. Read <a href="/methodology/">our methodology</a> and our <a href="/disclosures/">disclosures policy</a> for full transparency.',
]

WHEN_HEADING = "When Is an Inlay or Onlay Recommended?"
WHEN = [
    "An inlay or onlay is recommended when a tooth has moderate-to-large decay, a fracture, or a failing amalgam filling. The tooth is too damaged for a simple filling but strong enough to avoid a full crown. Clinicians choose indirect restorations when preserving natural tooth structure is the priority.",
    "<strong>Emergency alert:</strong> If you experience severe dental pain, swelling, or trauma, visit your nearest hospital emergency department or call 000. This guide is for planned restorative care.",
]

WHEN_ALERT = "If you have severe pain, uncontrolled bleeding, or facial swelling that affects breathing or vision, call 000 or go to the nearest hospital emergency department immediately."

WHO_HEADING = "Which are the top 10 inlays and onlays in Australia?"
WHO_TOP10 = "The ten clinics below are ranked from 1 to 10. Ranks 1-3 are featured entries."

TOP10 = [
    {"rank": 1, "name": "Placeholder Clinic", "location": "Australia", "featured": True, "rating": "", "pricing": "", "hours": "", "address": "", "phone": "", "website": "", "body": [""]},
]

COST_HEADING = "Inlays and Onlays Cost in Australia"
COST = [
    "An inlay or onlay in Australia costs between $350 and $2,200 per tooth, depending on the material. The table below lists typical price ranges for the full process, including consultation, imaging, and material options.",
    "Medicare does not generally cover inlays or onlays for adults. Private health insurance (Bupa, Medibank, HCF, HBF) typically covers these treatments under \"major dental\" extras. Check your benefit schedule and out-of-pocket cap before proceeding. Lab fees are normally included in the quoted price, but confirm this with the clinic. Some clinics charge a premium for CEREC same-day porcelain restorations.",
]
COST_PRICES = [
    ("Initial Consultation", "$50 – $120"),
    ("X-rays (per radiograph)", "$30 – $75"),
    ("Digital Scan / Impression", "$50 – $150"),
    ("Composite Resin Inlay/Onlay", "$350 – $650 per tooth"),
    ("Porcelain/Ceramic Inlay", "$850 – $1,600 per tooth"),
    ("Porcelain/Ceramic Onlay", "$1,000 – $2,200 per tooth"),
    ("Gold Inlay/Onlay", "$950 – $1,800 per tooth"),
]
COST_AFTER = [
    'See our <a href="/blog/">dental costs guide</a> for full fee breakdowns.',
]

CHOOSE_HEADING = "How to Choose a Dentist for Inlays and Onlays"
CHOOSE_INTRO = "Ask these questions before you book."
CHOOSE_CRITERIA = [
    ("Look for practices offering porcelain, ceramic, or zirconia for durability and aesthetics. Composite resin is a more affordable option but may not last as long as porcelain. Gold is rarely used today but is extremely durable. 2", ""),
    ("CEREC technology allows a single appointment with digital scanning, milling, and cementation. For busy schedules, this is a major convenience factor. Ask about the availability of same-day inlays and onlays. 3", ""),
    ("A transparent practice provides a detailed written quote before any work begins, including lab fees, materials, and anaesthetic charges. This helps you compare options and budget effectively. 4", ""),
    ("Inlays and onlays require precise bonding techniques and laboratory coordination. Ask the dentist how many they have placed and their success rate. Experienced clinicians provide better long-term results. 5", ""),
]
CHOOSE_AFTER = []

METHODOLOGY_HEADING = "How We Ranked the Top 10 Inlays and Onlays Clinics in Australia"
METHODOLOGY = [
    "We ranked these clinics using the criteria below."
]
METHODOLOGY_CRITERIA = [
    "The ranking methodology evaluates each clinic on eight criteria. The result is a comprehensive, trustworthy list for Australian readers.",
    "Dedicated inlays-and-onlays page. Clinics with a specific page dedicated to inlays and onlays were prioritised, as this indicates a strong focus on the service.",
    "Geographic coverage. The list covers major Australian cities (Sydney and Melbourne) and surrounding suburbs, ensuring readers across the country can find a suitable option.",
    "Verifiable contact details. Clinics with confirmed phone numbers and addresses were favoured. Where information was pending, it has been flagged for verification.",
    "Material options. Clinics offering modern materials such as porcelain, ceramic, zirconia, and composite resin scored higher.",
    "Technology and equipment. Practices offering CEREC same-day digital scanning and milling were noted for advanced technology.",
    "Patient reviews and reputation. Online patient reviews and general reputation were considered. Specific testimonials have not been invented.",
    "Pricing transparency. Clinics that provide fee information or clear treatment plan options were preferred.",
    "Website quality and information. The professionalism, detail, and accuracy of each clinic's website were evaluated as part of the ranking.",
]
METHODOLOGY_AFTER = []

FAQ_HEADING = "Frequently Asked Questions"
FAQS = [
    ("What's the difference between an inlay and an onlay?", "**An inlay fits inside the cusps of a tooth; an onlay covers one or more cusps.** An inlay is used when there is decay or damage but the cusp structure is healthy enough to support the tooth without capping. An onlay, sometimes called a \"partial crown,\" protects more of the tooth while preserving more natural structure than a full [dental crown](/australia/dental-crowns/)."),
    ("Are inlays and onlays better than dental fillings?", "**Inlays and onlays are stronger and longer-lasting than direct fillings for moderate-to-large cavities.** They are custom-made in a laboratory, providing superior fit and better sealing of the tooth. However, they cost more and require two appointments, or one with CEREC. Direct [dental fillings](/australia/dental-fillings/) suit small cavities."),
    ("How long do porcelain inlays and onlays last?", "**Porcelain inlays and onlays last 10 to 15 years or longer** with good oral hygiene and regular check-ups. Longevity depends on oral hygiene, bite force, and teeth grinding. A night guard extends the life of the restoration."),
    ("Can I get a same-day inlay or onlay in Australia?", "**Yes, many Sydney and Melbourne practices offer same-day CEREC restorations.** A digital scan of the prepared tooth, on-site milling, and cementation are completed in a single appointment. This removes the need for a temporary restoration and a second visit. Read about [same-day crowns and CEREC](/blog/same-day-crowns-and-cerec/)."),
    ("Do inlays and onlays hurt?", "**The procedure is performed under local anaesthetic and is generally painless.** It is comparable to having a standard dental filling placed. Some patients experience mild sensitivity after the anaesthetic wears off, but this usually resolves within a few days."),
    ("Will private health insurance cover inlays and onlays?", "**Most private health funds cover inlays and onlays under their \"major dental\" or \"restorative\" categories.** The benefit depends on your fund, level of cover, and the dentist's fee. Funds typically pay 50%–70% of the item fee. Medicare does not generally cover these procedures for adults. See typical [dental costs in Australia](/blog/dental-costs-in-australia/)."),
    ("How much does an inlay or onlay cost in Australia?", "**Composite resin inlays and onlays cost $350–$650; porcelain restorations range from $1,000 to $2,200 per tooth.** The full price guide appears in the cost section above. Always ask for a written quote."),
    ("How do I choose a dentist for inlays and onlays?", "**Ask about their experience with indirect restorations, the materials they use, CEREC same-day options, and request a detailed written quote.** Check patient reviews and confirm the clinic's location and hours. Use our guide on [how to choose a dentist](/blog/how-to-choose-a-dentist/)."),
]

CTA_TITLE = "Are you an Inlays and Onlays provider in Australia?"
CTA_TEXT = "Apply to be featured in our next update."

DISCLOSURE = "Practices in positions 1 to 3 are paid placements with do-follow links. Practices in positions 4 to 10 are listed editorially with no-follow links. Paid placement never affects positions 4 to 10."

SCHEMAS = []  # built by the template's _build_schemas() in manual workflow