"""Content for /australia/inlays-and-onlays/ — Top 10 Inlays and Onlays in Australia.
Generated by service_pipeline.py (2026-08-30). Manually corrected with verified clinic data."""
import json

META_TITLE = "Top 10 Inlays and Onlays in Australia"
META_DESC = "Compare the top 10 inlays and onlays dentists in Australia. Read our guide to porcelain restorations, costs, and FAQs."
H1 = "Top 10 Inlays and Onlays in Australia"
BADGE = "Top 10 — Reviewed & Ranked"

INTRO = [
    "Inlays and onlays are indirect dental restorations used to repair a decayed or damaged tooth that is too compromised for a simple filling but does not yet require a full crown. An inlay fits within the tooth's cusps (the points of the tooth), while an onlay covers one or more cusps for additional support. Both are typically made of porcelain, composite resin or gold, and are fabricated in a dental laboratory before being cemented into place.",
    "This ranking compares 10 Australian clinics that offer inlay and onlay restorations across Sydney and Melbourne. We assessed verified addresses, phones, restorative dentistry expertise, CEREC same-day technology, pricing transparency and patient reviews, so you can compare providers before booking.",
    'Positions 1 to 3 are paid placements with do-follow links. Positions 4 to 10 are editorial selections with no-follow links. Browse our complete directory of <a href="/australia/">all dental services across Australia</a>. Read <a href="/methodology/">our methodology</a> and our <a href="/disclosures/">disclosures policy</a> for full transparency.',
]

WHEN_HEADING = "When Is an Inlay or Onlay Recommended?"
WHEN = [
    "Your dentist may recommend an inlay or onlay if you have:",
    "Common reasons for an inlay or onlay: moderate tooth decay or damage that is too large for a standard filling, a cracked or fractured tooth where the remaining structure is still sound, replacing an old or failing filling, or when a tooth needs reinforcement after root canal treatment. Inlays and onlays preserve more natural tooth structure than a crown, making them a conservative restorative option.",
    "<strong>Emergency alert:</strong> If you experience severe dental pain, swelling, or trauma, visit your nearest hospital emergency department or call 000. This guide is for planned restorative care.",
]

WHEN_ALERT = "If you have severe pain, uncontrolled bleeding, or facial swelling that affects breathing or vision, call 000 or go to the nearest hospital emergency department immediately."

WHO_HEADING = "Which are the top 10 inlays and onlays dentists in Australia?"
WHO_TOP10 = "The ten clinics below are ranked from 1 to 10. Ranks 1-3 are featured entries."

TOP10 = [
    {"rank": 1, "name": "Hyde Park Dental Care", "location": "Sydney CBD, NSW", "featured": True, "rating": "4.8/5 (Google)", "pricing": "Inlay/onlay from $1,200", "hours": "Mon–Fri plus selected Saturdays", "address": "Suite 10, Lower Level, Hyde Park Square, 227 Elizabeth Street, Sydney NSW 2000", "phone": "02 9267 9526", "website": "https://www.hydeparkdentalcare.com.au", "body": ["Hyde Park Dental Care is a modern practice located in Hyde Park Square in the Sydney CBD, offering restorative dentistry including porcelain inlays and onlays. The team combines conservative tooth-preserving techniques with high-quality materials to restore damaged molars and premolars while keeping as much natural tooth structure as possible.", "Located at the corner of Elizabeth and Bathurst Streets, directly opposite Hyde Park, the clinic is easily accessible by train, bus and light rail. They are a preferred provider for major health funds and offer on-the-spot HICAPS claiming."]},
    {"rank": 2, "name": "Dental 266", "location": "Burwood, NSW", "featured": True, "rating": "4.8/5 (Google)", "pricing": "Inlay/onlay from $1,100", "hours": "Mon–Fri 9:00am–5:30pm, Sat 9:00am–1:00pm", "address": "Shop 4, 4/266-274 Burwood Rd, Burwood NSW 2134", "phone": "02 9051 0600", "website": "https://www.dental266.com.au", "body": ["Dental 266 is a modern practice in Burwood offering comprehensive restorative dentistry, including custom-fabricated inlays and onlays. Their dentists use digital impressions and work with skilled dental laboratories to produce precise, durable porcelain restorations that match the natural shade of your teeth.", "Conveniently located on Burwood Road with easy access from the Burwood train station and Westfield, the practice is a popular choice for patients across the inner west. They accept all major health funds."]},
    {"rank": 3, "name": "Sydney Cosmetic Dentist", "location": "Bondi Junction, NSW", "featured": True, "rating": "4.8/5 (Google)", "pricing": "Inlay/onlay from $1,200", "hours": "Mon–Fri 9:00am–5:00pm", "address": "Shop 2, Eclipse Building, 1 Adelaide Street, Bondi Junction NSW 2022", "phone": "02 5502 1236", "website": "https://www.sydneycosmeticdentist.com.au", "body": ["Sydney Cosmetic Dentist is an Eastern-suburbs clinic dedicated to high-quality restorative and cosmetic dentistry, including porcelain inlays and onlays. Their dentists focus on conservative restorations that preserve natural tooth structure, using premium ceramic materials for strength and aesthetics.", "Located in the Eclipse Building at Bondi Junction, the practice is a short walk from the Bondi Junction interchange. They offer detailed treatment planning and transparent pricing."]},
    {"rank": 4, "name": "Southern Sydney Dental Care", "location": "Ramsgate, NSW", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Inlay/onlay from $1,000", "hours": "Mon–Fri 8:30am–5:00pm", "address": "302 Rocky Point Road, Ramsgate NSW 2217", "phone": "02 9529 3760", "website": "https://www.southernsydneydentalcare.com.au", "body": ["Southern Sydney Dental Care is a family-oriented practice in Ramsgate offering restorative dentistry including inlays and onlays. The experienced team provides conservative, high-quality restorations for damaged teeth, with a focus on preserving healthy tooth structure and long-term durability.", "Located on Rocky Point Road in the St George area, the clinic is a Bupa preferred provider offering on-the-spot claims. Convenient parking is available."]},
    {"rank": 5, "name": "Homebush Dental Practice", "location": "Homebush, NSW", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Inlay/onlay from $1,000", "hours": "Mon–Fri 9:00am–5:30pm, Sat 9:00am–2:00pm", "address": "16 Rochester Street, Homebush NSW 2140", "phone": "02 8084 7242", "website": "https://www.homebushdentalpractice.com.au", "body": ["Homebush Dental Practice is a well-established family practice offering comprehensive restorative dentistry, including custom inlays and onlays. Their dentists provide conservative tooth-preserving treatment options for patients with moderate decay or damage, using high-quality porcelain restorations.", "Open six days a week with gap-free options for eligible health fund members, the practice is conveniently located in Homebush near the train station and major shopping."]},
    {"rank": 6, "name": "Dental Health", "location": "Melbourne CBD, VIC", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Inlay/onlay from $1,200", "hours": "Mon–Fri 8:30am–5:30pm", "address": "Level 4, 175 Collins Street, Melbourne VIC 3000", "phone": "03 9650 2909", "website": "https://www.dentalhealth.com.au", "body": ["Dental Health is a long-established Melbourne CBD practice offering comprehensive restorative dentistry, including porcelain inlays and onlays. The experienced team provides conservative restorations that preserve natural tooth structure while restoring strength and function to damaged teeth.", "Located in the heart of the Collins Street medical and financial precinct, the practice is easily accessible from Flinders Street and Melbourne Central stations."]},
    {"rank": 7, "name": "Healthy Smiles Australia", "location": "Niddrie, VIC", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Inlay/onlay from $1,100", "hours": "Mon–Fri 9:00am–5:00pm, Sat 9:00am–1:00pm", "address": "8/344 Keilor Rd, Niddrie VIC 3042", "phone": "+61 3 9020 6075", "website": "https://www.healthysmilesaustralia.com.au", "body": ["Healthy Smiles Australia is a family-friendly practice in Niddrie offering comprehensive restorative dentistry, including inlays and onlays. Their dentists focus on conservative, tooth-preserving restorations and use modern technology to deliver precise, durable results.", "Open six days a week with HICAPS on-the-spot claiming and a new patient special, the practice is a popular choice for families across Melbourne's north-west."]},
    {"rank": 8, "name": "Dentist Melbourne", "location": "Greensborough, VIC", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Inlay/onlay from $1,000", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "137 Grimshaw Street, Greensborough VIC 3088", "phone": "(03) 9435 6063", "website": "https://www.dentist-melbourne.com.au", "body": ["Dentist Melbourne is a modern practice in Greensborough offering restorative dentistry including custom inlays and onlays. The experienced team provides conservative treatment options that preserve healthy tooth structure, using high-quality ceramic materials for long-lasting results.", "Conveniently located on Grimshaw Street with easy access from the Greensborough Plaza and public transport, the practice accepts all major health funds."]},
    {"rank": 9, "name": "Smile Solutions", "location": "Melbourne CBD, VIC", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Inlay/onlay from $1,300", "hours": "Mon–Fri 8:00am–6:00pm, Sat 9:00am–5:00pm", "address": "Level 1, 220 Collins St, Manchester Unity Building, Melbourne VIC 3000", "phone": "(03) 9650 4920", "website": "https://www.smilesolutions.com.au", "body": ["Smile Solutions is one of Melbourne's largest dental practices, located in the heritage Manchester Unity Building on Collins Street. Their restorative dentistry team provides premium porcelain inlays and onlays, coordinated with in-house specialists where needed for complex cases.", "The practice houses multiple specialists under one roof, so your restorative treatment can be planned and delivered in a single, coordinated visit. Open six days a week."]},
    {"rank": 10, "name": "Vogue Smiles Melbourne", "location": "Noble Park North, VIC", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Inlay/onlay from $1,000", "hours": "Mon–Fri 9:00am–5:30pm, Sat 9:00am–1:00pm", "address": "97 Browns Road, Noble Park North VIC 3174", "phone": "(03) 9629 7664", "website": "https://www.voguesmilesmelbourne.com.au", "body": ["Vogue Smiles Melbourne is a modern practice in Melbourne's south-east offering comprehensive restorative dentistry, including porcelain inlays and onlays. The experienced team provides conservative, tooth-preserving restorations with a focus on natural aesthetics and long-term durability.", "Conveniently located on Browns Road with on-site parking, the practice is easily accessible from the Monash Freeway and surrounding south-eastern suburbs."]},
]

COST_HEADING = "How Much Do Inlays and Onlays Cost in Australia?"
COST = [
    "The cost of an inlay or onlay in Australia depends on the material used (porcelain, composite or gold), the number of cusps covered and the laboratory fees involved. As an indirect restoration, an inlay or onlay is generally more expensive than a direct filling but less than a full crown.",
    "<strong>Funding Note:</strong> Private health insurance extras policies typically cover a percentage of the restorative item depending on your level of cover. Many practices offer CEREC same-day restorations, which can reduce visits to a single appointment. Always obtain an itemised written quote before treatment begins.",
]
COST_PRICES = [
    ("Consultation and examination", "$50 – $120"),
    ("Composite inlay (per tooth)", "$500 – $900"),
    ("Porcelain inlay (per tooth)", "$1,000 – $1,600"),
    ("Porcelain onlay (per tooth)", "$1,200 – $2,000"),
    ("Gold inlay (per tooth)", "$1,200 – $2,200"),
    ("CEREC same-day inlay/onlay", "$1,000 – $1,800"),
]
COST_AFTER = [
    'See our <a href="/blog/">dental costs guide</a> for full fee breakdowns.',
]

CHOOSE_HEADING = "How to Choose an Inlay or Onlay Dentist in Australia"
CHOOSE_INTRO = "Ask these questions before you book."
CHOOSE_CRITERIA = [
    ("Is an inlay or onlay the right restoration for my tooth?", "Your dentist should explain why an inlay or onlay is preferred over a direct filling or a full crown, based on the size of the damage and how much healthy tooth structure remains. A conservative restoration preserves more natural tooth."),
    ("Does the clinic offer CEREC same-day restorations?", "Some practices offer CEREC technology, allowing your inlay or onlay to be designed, milled and fitted in a single visit. This avoids the need for a temporary restoration and a second appointment."),
    ("What material is recommended and why?", "Porcelain offers the best aesthetics, composite is more affordable, and gold is extremely durable for back teeth. Ask your dentist which material best suits the location of the tooth and your budget."),
    ("Can I see examples of previous restorative work?", "A reputable practice should be able to show you before-and-after photos of inlay and onlay cases, giving you confidence in the quality of their laboratory work and fitting."),
    ("Is the quote itemised and does my health fund cover it?", "Ask for a written itemised quote covering the consultation, the restoration itself, laboratory fees and any anaesthetic or temporary costs. Check your extras cover and whether the practice offers HICAPS on-the-spot claiming."),
]
CHOOSE_AFTER = []

METHODOLOGY_HEADING = "How We Ranked the Top 10 Inlay and Onlay Providers"
METHODOLOGY = [
    "We ranked these clinics using the criteria below."
]
METHODOLOGY_CRITERIA = [
    "Every clinic in this ranking was assessed against the same 8 criteria. Points were weighted towards verified data and patient value.",
    "Verified contact details — Practices with a confirmed full street address and live phone number scored highest.",
    "Restorative dentistry expertise — Experience with indirect restorations, inlays, onlays and crowns.",
    "Materials and technology — Use of premium porcelain/composite, digital impressions and CEREC same-day options.",
    "Pricing transparency — Published fee schedules, live price lists or clear itemised quotes before booking.",
    "Patient reviews and reputation — Quality and volume of Google and practice-published patient reviews.",
    "Location accessibility — CBD access, public transport, parking and suitability for working patients.",
    "Health fund and HICAPS processing — On-the-spot rebates and preferred provider arrangements.",
    "Conservative dentistry approach — Preference for preserving natural tooth structure wherever possible.",
    "Ratings change as patient feedback and practice details change. We re-verify clinic data periodically; if you spot an error, contact us so we can update this ranking.",
]
METHODOLOGY_AFTER = []

FAQ_HEADING = "Frequently Asked Questions"
FAQS = [
    ("What is the difference between an inlay and an onlay?", "An inlay fits within the cusps (the pointed biting surfaces) of a tooth, repairing the area between them. An onlay extends over one or more cusps, providing additional support when the tooth needs more coverage. Both preserve more natural tooth structure than a full crown."),
    ("How much does an inlay or onlay cost in Australia?", "Prices typically range from $500 for a composite inlay to $2,200 for a gold onlay. Porcelain inlays cost around $1,000–$1,600 and porcelain onlays $1,200–$2,000. CEREC same-day restorations cost $1,000–$1,800. Private health insurance extras can reduce the out-of-pocket cost significantly."),
    ("How long do inlays and onlays last?", "With good oral hygiene and regular check-ups, a well-fitted porcelain or gold inlay/onlay typically lasts 10 to 15 years or longer. Their longevity depends on the material, the quality of the fit and your home care."),
    ("Does an inlay or onlay procedure hurt?", "The procedure is performed under local anaesthetic, so you should not feel pain during treatment. You may experience mild sensitivity for a few days after the restoration is fitted, which usually settles quickly."),
    ("Are inlays and onlays better than crowns?", "For teeth with moderate damage where a significant portion of the natural tooth structure remains, inlays and onlays are often the more conservative choice — they preserve more healthy tooth than a crown. A crown is recommended when the tooth is too badly damaged for an inlay or onlay to provide adequate support."),
    ("How many appointments does an inlay or onlay take?", "With traditional laboratory fabrication, an inlay or onlay usually takes two appointments: one to prepare the tooth and take impressions, and a second to fit the restoration. Practices offering CEREC same-day technology can complete the entire procedure in a single visit."),
]

CTA_TITLE = "Are you an Inlays and Onlays provider in Australia?"
CTA_TEXT = "Apply to be featured in our next update."

DISCLOSURE = "Practices in positions 1 to 3 are paid placements with do-follow links. Practices in positions 4 to 10 are listed editorially with no-follow links. Paid placement never affects positions 4 to 10."

SCHEMAS = []  # built by the template's _build_schemas() in manual workflow