"""Content for /australia/oral-hygiene/ — Top 10 Oral Hygiene in Australia.
Generated by service_pipeline.py (2026-08-30). Manually corrected with verified clinic data."""
import json

META_TITLE = "Top 10 Oral Hygiene in Australia"
META_DESC = "Find the best oral hygiene clinics in Australia for scale and clean, gum care, and check-ups. Compare vetted providers in Sydney, Melbourne, Brisbane."
H1 = "Top 10 Oral Hygiene in Australia"
BADGE = "Top 10 — Reviewed & Ranked"

INTRO = [
    "Good oral hygiene is the foundation of lifelong dental health. In Australia, professional oral hygiene services — including scale and cleans, gum care, fluoride application and personalised preventive advice — play a crucial role in preventing tooth decay, gum disease and more serious dental problems. Regular professional cleanings complement your home brushing and flossing routine.",
    "This ranking compares 10 oral hygiene and preventive dentistry providers across Sydney, Melbourne, Brisbane and beyond. We assessed verified addresses, phones, hygienist qualifications, pricing transparency, patient reviews and preventive care focus, so you can compare providers before booking your next check-up and clean.",
    'Positions 1 to 3 are paid placements with do-follow links. Positions 4 to 10 are editorial selections with no-follow links. Browse our complete directory of <a href="/australia/">all dental services across Australia</a>. Read <a href="/methodology/">our methodology</a> and our <a href="/disclosures/">disclosures policy</a> for full transparency.',
]

WHEN_HEADING = "When Should You See a Dental Hygienist?"
WHEN = [
    "You should book an oral hygiene appointment every 6 to 12 months, or sooner if you experience bleeding gums, persistent bad breath, tooth sensitivity, heavy plaque or tartar build-up, or if you are a smoker, pregnant, diabetic or undergoing orthodontic treatment — all of which increase your risk of gum disease.",
    "The Australian Dental Association recommends a professional scale and clean at the interval your dentist recommends based on your individual risk. Preventive hygiene visits catch problems early, when they are cheaper and easier to treat.",
    "<strong>Emergency alert:</strong> If you have severe toothache, facial swelling, uncontrolled bleeding or trauma to the teeth, see a dentist urgently or present to a hospital emergency department.",
]

WHEN_ALERT = "If you have severe pain, uncontrolled bleeding, or facial swelling that affects breathing or vision, call 000 or go to the nearest hospital emergency department immediately."

WHO_HEADING = "Which are the top 10 oral hygiene clinics in Australia?"
WHO_TOP10 = "The ten clinics below are ranked from 1 to 10. Ranks 1-3 are featured entries."

TOP10 = [
    {"rank": 1, "name": "Penrith Dental Clinic", "location": "Penrith, NSW", "featured": True, "rating": "4.8/5 (Google)", "pricing": "Scale and clean $90–$250", "hours": "Mon–Fri 9:00am–5:30pm, Sat 9:00am–1:00pm", "address": "Suite 4A, Penrith Medical Centre, 61-79 Henry St, Penrith NSW 2750", "phone": "(02) 4721 7771", "website": "https://www.penrithdentalclinic.com.au", "body": ["Penrith Dental Clinic is a well-established practice in Western Sydney offering comprehensive preventive and oral hygiene care, including professional scale and cleans. The experienced team focuses on preventive dentistry, helping patients maintain healthy gums and avoid decay through regular hygiene appointments and tailored home-care advice.", "Located within the Penrith Medical Centre on Henry Street, the clinic is easily accessible with ample parking and is open six days a week. They accept all major health funds and offer on-the-spot HICAPS claiming."]},
    {"rank": 2, "name": "Pacific Smiles Dental", "location": "Charlestown, NSW", "featured": True, "rating": "4.6/5 (Google)", "pricing": "Scale and clean $100–$280", "hours": "Mon–Fri 9:00am–5:30pm, Sat 9:00am–1:00pm", "address": "5 Pearson St, Charlestown NSW 2290", "phone": "(02) 4943 4299", "website": "https://www.pacificsmilesdental.com.au", "body": ["Pacific Smiles Dental is one of Australia's largest dental networks, and the Charlestown practice offers comprehensive preventive care including professional scale and cleans by qualified dental hygienists. The team focuses on gentle, thorough hygiene appointments and patient education.", "Conveniently located on Pearson Street in Charlestown, the practice is open six days a week and offers gap-free check-up and clean appointments for many health fund members."]},
    {"rank": 3, "name": "DentaPex", "location": "Dee Why, NSW", "featured": True, "rating": "4.7/5 (Google)", "pricing": "Check-up and clean $150–$300", "hours": "Mon–Fri 9:00am–7:00pm, Sat 9:00am–5:00pm, Sun 9:00am–1:00pm", "address": "842 Pittwater Rd, Dee Why NSW 2099", "phone": "1300 376 453", "website": "https://www.dentapex.com.au", "body": ["DentaPex is a modern multi-location practice on Sydney's Northern Beaches, offering comprehensive oral hygiene and preventive care including professional scale and cleans. The friendly team is dedicated to helping patients maintain healthy smiles through regular hygiene appointments and preventive education.", "Located on Pittwater Road in Dee Why with easy parking, the practice is open seven days a week and accepts all health funds with on-the-spot claiming."]},
    {"rank": 4, "name": "Bupa Dental Brisbane", "location": "Brisbane CBD, QLD", "featured": False, "rating": "4.6/5 (Google)", "pricing": "Scale and clean $100–$280", "hours": "Mon–Fri 9:00am–5:30pm", "address": "27 Adelaide St, Brisbane City QLD 4000", "phone": "(07) 3228 2400", "website": "https://www.bupadental.com.au", "body": ["Bupa Dental Brisbane offers comprehensive oral hygiene services in the heart of the Brisbane CBD, with experienced hygienists providing professional scale and cleans, gum care and preventive treatment. As part of the Bupa Dental network, the practice offers gap-free preventive appointments for eligible Bupa members.", "Conveniently located on Adelaide Street near the Queen Street Mall, the practice is easily accessible by train, bus and ferry. On-the-spot health fund claiming is available."]},
    {"rank": 5, "name": "LifeCare Dental", "location": "Perth CBD, WA", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Scale and clean $100–$280", "hours": "Mon–Fri 8:30am–5:30pm", "address": "T18, 200-204 Murray St, Perth WA 6000", "phone": "(08) 9221 2777", "website": "https://www.lifecaredental.com.au", "body": ["LifeCare Dental is a modern practice in the Perth CBD offering comprehensive preventive and oral hygiene care, including professional scale and cleans by experienced hygienists. The team emphasises evidence-based preventive dentistry and patient education.", "Located in the Forrest Chase shopping complex on Murray Street, the practice is easily accessible from the Perth train station and all CBD bus routes. They accept all major health funds."]},
    {"rank": 6, "name": "Dental on Clarendon", "location": "South Melbourne, VIC", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Hygiene appointment $120–$260", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "383 Clarendon St, South Melbourne VIC 3205", "phone": "03 9690 3285", "website": "https://www.dentalonclarendon.com.au", "body": ["Dental on Clarendon is a modern family practice in South Melbourne offering comprehensive oral hygiene services, including professional scale and cleans and periodontal maintenance. The experienced hygienist team provides gentle, thorough cleans and personalised preventive advice.", "Conveniently located on Clarendon Street with tram access and nearby parking, the practice is a popular choice for South Melbourne, Albert Park and Port Melbourne residents. They are a preferred provider for major health funds."]},
    {"rank": 7, "name": "Smile In Style Dentistry", "location": "Moonee Ponds, VIC", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Check-up and clean $150–$300", "hours": "Mon–Fri 8:30am–5:30pm", "address": "821 Mt. Alexander Road, Moonee Ponds VIC 3039", "phone": "03 8001 6021", "website": "https://www.smileinstyle.com.au", "body": ["Smile In Style Dentistry is a modern practice in Melbourne's inner north-west offering comprehensive oral hygiene and preventive care, including professional scale and cleans. The patient-centred team focuses on comfortable, thorough hygiene appointments and long-term preventive planning.", "Located on Mount Alexander Road in Moonee Ponds with easy tram access and parking, the practice is a popular choice for families across Melbourne's north-west."]},
    {"rank": 8, "name": "Dental Couture", "location": "Sunbury, VIC", "featured": False, "rating": "4.7/5 (Google)", "pricing": "General exam and hygiene from $250", "hours": "Mon–Fri 9:00am–5:30pm", "address": "12 Powlett St, Sunbury VIC 3429", "phone": "13 26 88", "website": "https://www.dentalcouture.com.au", "body": ["Dental Couture is a modern practice in Sunbury offering comprehensive general examination and hygiene services in Melbourne's north-west. The team provides professional scale and cleans, gum care and preventive treatment in a comfortable, welcoming environment.", "Conveniently located on Powlett Street in the Sunbury town centre with on-site parking, the practice is easily accessible from the Sunbury train line. They offer flexible payment options."]},
    {"rank": 9, "name": "Sunshine Dental Group", "location": "Sunshine, VIC", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Check-up and clean $120–$260", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "57 Devonshire Road, Sunshine VIC 3020", "phone": "(03) 9133 8657", "website": "https://www.sunshinedentalgroup.com.au", "body": ["Sunshine Dental Group is a well-established family practice in Melbourne's west offering comprehensive oral hygiene and preventive care, including professional scale and cleans. The experienced team is dedicated to helping patients maintain healthy gums and teeth through regular hygiene appointments.", "Located on Devonshire Road in Sunshine, the practice is easily accessible from the Sunshine train station and Western Ring Road. They accept all major health funds with on-the-spot claiming."]},
    {"rank": 10, "name": "MGA Dental", "location": "Surfers Paradise, QLD", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Check-up and clean $150–$300", "hours": "Mon–Fri 9:00am–5:30pm, Sat 9:00am–1:00pm", "address": "122 Salerno St, Surfers Paradise QLD 4217", "phone": "(07) 5539 9748", "website": "https://www.mgadental.com.au", "body": ["MGA Dental is a modern Gold Coast practice offering comprehensive preventive dentistry and oral hygiene care, including professional scale and cleans. The clinical team provides thorough hygiene appointments and personalised preventive advice to help patients maintain healthy smiles.", "Located on Salerno Street in the heart of Surfers Paradise, the practice is easily accessible from the Gold Coast Highway. They offer flexible payment options and accept all major health funds."]},
]

COST_HEADING = "How Much Does Oral Hygiene Treatment Cost in Australia?"
COST = [
    "The cost of a professional scale and clean in Australia varies by city, suburb and whether it is combined with a check-up. Prices typically reflect the hygienist's time, the extent of tartar removal required and the practice's location. The ranges below are indicative figures drawn from Australian Dental Association fee surveys and clinic published schedules.",
    "<strong>Funding Note:</strong> Medicare does not generally cover routine dental check-ups and cleans for adults. Private health insurance extras can reduce out-of-pocket costs significantly; some practices offer no-gap or known-gap appointments for insured patients. The Child Dental Benefits Schedule (CDBS) covers eligible children aged 2 to 17 for up to $1,013 in basic dental services over two years.",
]
COST_PRICES = [
    ("Dental check-up", "$50 – $120"),
    ("Scale and polish / professional clean", "$80 – $250"),
    ("Check-up and clean (combined)", "$120 – $300"),
    ("Periodontal maintenance (gum disease recall)", "$120 – $280"),
    ("Fluoride application (add-on)", "$25 – $70"),
    ("Radiographs / X-rays (per set)", "$40 – $120"),
]
COST_AFTER = [
    'See our <a href="/blog/">dental costs guide</a> for full fee breakdowns.',
]

CHOOSE_HEADING = "How to Choose an Oral Hygiene Clinic in Australia"
CHOOSE_INTRO = "Ask these questions before you book."
CHOOSE_CRITERIA = [
    ("Are their appointment hours convenient?", "Choose a practice with hours that suit your schedule. Many clinics offer early morning, evening and Saturday appointments, making it easier to fit regular 6- or 12-monthly hygiene visits into a busy routine."),
    ("What is the total cost and do they accept your health fund?", "Ask for a written quote covering the check-up, scale and clean and any X-rays, and confirm whether the practice is a preferred provider for your health fund. Gap-free or known-gap appointments can significantly reduce out-of-pocket costs."),
    ("Is the clinic focused on preventive care and hygiene?", "Look for practices with dedicated dental hygienists and a strong preventive focus. A good hygiene appointment includes professional cleaning, gum health assessment and personalised home-care advice."),
    ("What are the dentist or hygienist's qualifications and experience?", "Dental hygienists are university-trained oral health professionals. Ask about the experience of the hygiene team, particularly if you have gum disease or complex preventive needs."),
    ("What do existing patients say?", "Check Google and practice-published reviews for feedback on gentleness, thoroughness and communication. A practice with consistently positive reviews is more likely to provide a comfortable, high-quality hygiene experience."),
]
CHOOSE_AFTER = []

METHODOLOGY_HEADING = "How We Ranked the Top 10 Oral Hygiene Providers"
METHODOLOGY = [
    "We ranked these clinics using the criteria below."
]
METHODOLOGY_CRITERIA = [
    "Every clinic in this ranking was assessed against the same 8 criteria. Points were weighted towards verified data and patient value.",
    "Verified contact details — Practices with a confirmed full street address and live phone number scored highest.",
    "Hygiene and preventive care focus — Dedicated dental hygienists, scale and clean services and preventive treatment programs.",
    "Patient reviews and reputation — Quality and volume of Google and practice-published patient reviews.",
    "Pricing transparency — Published fee schedules, live price lists or clear quotes before booking.",
    "Location accessibility — CBD access, public transport, parking and suitability for families or workers.",
    "Health fund and HICAPS processing — On-the-spot rebates, gap-free offers and preferred provider arrangements.",
    "Children's and family care — Welcoming patients of all ages with appropriate preventive care.",
    "Technology and comfort — Modern equipment, digital X-rays and a comfortable, relaxing environment.",
    "Ratings change as patient feedback and practice details change. We re-verify clinic data periodically; if you spot an error, contact us so we can update this ranking.",
]
METHODOLOGY_AFTER = []

FAQ_HEADING = "Frequently Asked Questions"
FAQS = [
    ("What does a dental hygienist do in Australia?", "A dental hygienist is a university-trained oral health professional who provides professional scale and cleans, removes plaque and tartar, applies fluoride, assesses gum health and teaches personalised home-care techniques. They work alongside dentists to prevent and manage gum disease and tooth decay."),
    ("How often should I have a scale and clean?", "The Australian Dental Association recommends a professional scale and clean every 6 to 12 months for most people. Your dentist or hygienist may recommend more frequent visits (every 3–4 months) if you have gum disease, heavy tartar build-up, or other risk factors such as smoking or diabetes."),
    ("What is the difference between a dental check-up and an oral hygiene appointment?", "A dental check-up focuses on examining your teeth, gums and mouth for problems such as decay, gum disease and oral pathology, often with X-rays. An oral hygiene appointment (scale and clean) focuses on professionally cleaning your teeth, removing plaque and tartar, and maintaining gum health. Most practices combine the two in a single visit."),
    ("Does Medicare cover scale and clean appointments?", "Medicare does not cover routine dental scale and cleans for adults. Eligible children aged 2–17 can access the Child Dental Benefits Schedule (CDBS) for up to $1,013 over 2 calendar years. Private health insurance extras policies typically cover a percentage of the cost, and some practices offer gap-free appointments for members."),
    ("Can a hygienist remove stains and improve the look of my teeth?", "Yes. A professional scale and polish removes plaque, tartar and surface staining from tea, coffee and tobacco, leaving teeth cleaner and brighter. For deeper discolouration, your dentist can discuss professional teeth whitening options."),
    ("What should I do between hygiene visits to keep my gums healthy?", "Brush twice daily with a soft-bristled toothbrush and fluoride toothpaste, floss or use interdental brushes daily, and reduce sugary and acidic foods and drinks. Rinsing with an antibacterial mouthwash and staying hydrated also help. Your hygienist can tailor a home-care routine to your needs."),
    ("Is a scale and clean painful and what should I expect afterwards?", "A scale and clean is generally comfortable. You may feel some scraping or vibration, and mild sensitivity for a few days afterwards, especially if you have significant tartar build-up. Your hygienist can use a numbing gel if needed. Teeth may feel smoother and gums may bleed slightly if they are inflamed — this settles as gum health improves."),
]

CTA_TITLE = "Are you an Oral Hygiene provider in Australia?"
CTA_TEXT = "Apply to be featured in our next update."

DISCLOSURE = "Practices in positions 1 to 3 are paid placements with do-follow links. Practices in positions 4 to 10 are listed editorially with no-follow links. Paid placement never affects positions 4 to 10."

SCHEMAS = []  # built by the template's _build_schemas() in manual workflow