"""Content for /australia/oral-medicine/ — Top 10 Oral Medicine in Australia.
Generated by service_pipeline.py (2026-08-30)."""
import json

META_TITLE = "Top 10 Oral Medicine in Australia"
META_DESC = "Compare the top 10 oral medicine in Australia."
H1 = "Top 10 Oral Medicine in Australia"
BADGE = "Top 10 — Reviewed & Ranked"

INTRO = [
    "Oral medicine is the dental specialty concerned with diagnosing and managing medical conditions of the mouth, jaws, salivary glands and surrounding facial structures. Persistent mouth ulcers, white or red patches, dry mouth, burning sensations and unexplained oral pain can all signal underlying disease that requires more than a standard check-up. This guide reviews the top oral medicine providers in Australia to help you locate trustworthy care in your city. For a full overview of the specialty, read <a href=\"/blog/oral-medicine/\">What is Oral Medicine?</a>.",
    "Oral medicine services in Australia come from two main sources. Registered specialists, often based in public hospitals, manage complex mucosal and salivary gland disease. Experienced general dentists in private practice provide mucosal assessments, biopsies and screening for common oral conditions. Long public waiting lists drive many patients toward private clinics in Sydney, Melbourne and other capitals. The list below ranks both clinical providers and reputable online booking and directory platforms that help patients find care. Start with the <a href=\"/australia/\">Australia Dental Guide</a> to see the full range of dental services available across the country.",
    'Positions 1 to 3 are paid placements with do-follow links. Positions 4 to 10 are editorial selections with no-follow links. Browse our complete directory of <a href="/australia/">all dental services across Australia</a>. Read <a href="/methodology/">our methodology</a> and our <a href="/disclosures/">disclosures policy</a> for full transparency.',
]

WHEN_HEADING = "When Is Oral Medicine Care Needed?"
WHEN = [
    "Oral medicine care is needed when oral symptoms persist for more than two to three weeks or when they suggest a condition beyond routine dental disease. Most oral conditions are harmless and resolve on their own, but some signal serious underlying disease. Seek an oral medicine assessment if you experience any of the following:",
    "⚠️ <strong>Emergency warning:</strong> If you experience sudden swelling of the face or throat, difficulty breathing, severe bleeding from the mouth that will not stop, or a rapidly growing lump, call 000 immediately or go to your nearest hospital emergency department. Do not wait for a dental appointment.",
]

WHEN_ALERT = "If you have severe pain, uncontrolled bleeding, or facial swelling that affects breathing or vision, call 000 or go to the nearest hospital emergency department immediately."

WHO_HEADING = "Which are the top 10 oral medicine in Australia?"
WHO_TOP10 = "The ten clinics below are ranked from 1 to 10. Ranks 1-3 are featured entries."

TOP10 = [
    {"rank": 1, "name": "Placeholder Clinic", "location": "Australia", "featured": True, "rating": "", "pricing": "", "hours": "", "address": "", "phone": "", "website": "", "body": [""]},
]

COST_HEADING = "How Much Does Oral Medicine Cost in Australia?"
COST = [
    "Oral medicine costs vary widely depending on whether you are seen in a public hospital clinic, a private specialist practice or a general dental surgery. Public hospital clinics offer subsidised care but typically have long waiting lists and require a referral. The price ranges below reflect typical private fees in Australian cities as at 2025 and should be used as a guide only.",
    "Medicare may cover part of the cost for medically necessary biopsies or excisions performed in a public hospital setting. Private health insurance extras can also contribute toward specialist consultations and minor surgical procedures if your level of cover includes dental or oral surgery. Always confirm fees, item numbers and out-of-pocket costs with the clinic and your insurer before proceeding.",
]
COST_PRICES = [
    ("General dental check-up with oral mucosal screening", "$50–$120"),
    ("Specialist initial consultation (oral medicine)", "$180–$350"),
    ("Mucosal biopsy (performed in-surgery)", "$120–$300"),
    ("Histopathology examination (pathology lab fee)", "$100–$250"),
    ("Salivary flow test / sialometry", "$80–$200"),
    ("Follow-up consultation", "$90–$220"),
]
COST_AFTER = [
    'See our <a href="/blog/">dental costs guide</a> for full fee breakdowns.',
]

CHOOSE_HEADING = "How to Choose the Right Oral Medicine Provider"
CHOOSE_INTRO = "Ask these questions before you book."
CHOOSE_CRITERIA = [
    ("In Australia, oral medicine is a recognised dental specialty. Specialists are registered with the Dental Board of Australia and use the title \"Specialist Oral Medicine\" or \"Oral Medicine Practitioner.\" General dentists can manage common mucosal conditions, but complex or persistent disease is best reviewed by a registered specialist. You can verify a practitioner's registration on the Australian Health Practitioner Regulation Agency (AHPRA) public register. 2", ""),
    ("On-site digital radiography, intraoral cameras, sialometry and biopsy capability reduce the number of visits and speed up diagnosis. Clinics that must refer out for every diagnostic test can create delays and higher overall costs. Ask whether histopathology, blood tests and imaging are arranged through an integrated pathology network. 3", ""),
    ("Oral medicine often requires multiple appointments, so upfront fee transparency matters. Many private clinics provide written treatment plans with item numbers and costs. If cost is a barrier, use directories such as Zable to filter for bulk-billing practices or ask about public hospital options through your GP or dentist. 4", ""),
    ("Chronic oral conditions such as lichen planus and xerostomia need regular monitoring. A clinic close to work or home, with early morning, lunchtime or Saturday appointments, is more likely to keep you engaged in long-term care. Consider parking, public transport access and tele-health options for review appointments. 5", ""),
]
CHOOSE_AFTER = []

METHODOLOGY_HEADING = "How we ranked"
METHODOLOGY = [
    "We ranked these clinics using the criteria below."
]
METHODOLOGY_CRITERIA = [
]
METHODOLOGY_AFTER = []

FAQ_HEADING = "Frequently Asked Questions"
FAQS = [
    ("1. What kind of dentist treats oral medicine conditions?", "General dentists can assess and manage common oral mucosal problems such as mouth ulcers, candidiasis and minor soft tissue irritation. For complex or persistent conditions, including lichen planus, leukoplakia, autoimmune disorders and chronic dry mouth, a registered specialist in oral medicine is recommended. You can locate a registered specialist via the Dental Board of Australia register, ask your dentist for a referral, or browse the <a href=\"/australia/specialists/\">Find a Dental Specialist</a> directory. 2"),
    ("2. Do I need a referral from a GP to see an oral medicine specialist?", "Most private oral medicine specialists and general dental practices accept direct appointments without a referral. However, public hospital oral medicine clinics generally require a referral from a GP or dentist, and you may need to meet specific criteria to be placed on the waiting list. If you plan to claim through Medicare or private health extras, check your cover requirements before booking. Our guide to <a href=\"/blog/oral-medicine/\">What is Oral Medicine?</a> explains the specialist pathway in more detail. 3"),
    ("3. Will my private health insurance cover oral medicine treatments?", "Private health insurance extras may cover part of the cost of consultations, biopsies and minor surgical procedures, depending on your level of cover. Medicare may also contribute to medically necessary procedures such as excisions when performed in a public hospital setting. Always confirm the item numbers and out-of-pocket costs with your insurer and the treating clinic in advance. The <a href=\"/australia/\">Australia Dental Guide</a> lists how common dental services are typically covered. 4"),
    ("4. How long does it take to get results from a mouth biopsy?", "Biopsy results typically take one to three weeks, depending on the pathology service used and the complexity of the specimen. Your dentist or specialist will usually schedule a review appointment to explain the findings and discuss next steps. If the lesion requires urgent assessment, many pathology labs offer an expedited reporting service at an additional cost. Our guide to <a href=\"/blog/oral-cancer-screening/\">Oral Cancer Screening – What to Expect</a> outlines the biopsy and results pathway. 5"),
    ("5. Is oral lichen planus contagious?", "No, oral lichen planus is an autoimmune condition and is not contagious. It occurs when the immune system mistakenly attacks cells of the oral mucosa, leading to white lacy patches, redness or painful ulcers. Management focuses on symptom control and monitoring, and you should continue routine dental visits to track any changes. Learn more in <a href=\"/blog/oral-medicine/\">What is Oral Medicine?</a>. 6"),
    ("6. What causes recurrent mouth ulcers and how can I prevent them?", "Recurrent aphthous stomatitis (canker sores) is linked to stress, minor trauma, vitamin deficiencies (iron, B12 or folate), food sensitivities and hormonal changes. Some patients find that avoiding spicy or acidic foods, improving sleep and using a soft-bristled toothbrush reduces outbreaks. If ulcers last more than three weeks, bleed or grow in size, see a dentist for assessment. Use the <a href=\"/australia/specialists/\">Find a Dental Specialist</a> directory to locate a practitioner near you. 7"),
    ("7. What are the early signs of oral cancer I should look out for?", "Look for red or white patches that do not rub off, a sore that fails to heal within three weeks, a persistent lump or thickening in the cheek, difficulty swallowing, or unexplained numbness in the mouth. Early detection significantly improves outcomes, so book an oral cancer screening promptly if you notice any of these changes. Our guide on <a href=\"/blog/oral-cancer-screening/\">Oral Cancer Screening – What to Expect</a> explains the process in detail. 8"),
    ("8. Can oral medicine help with chronic dry mouth (xerostomia)?", "Yes. An oral medicine practitioner can identify the underlying cause of dry mouth, whether it is medication-related, linked to Sjögren's syndrome, or a result of radiotherapy, and recommend management options such as saliva substitutes, prescription stimulants and preventive care. For at-home tips, read our guide to <a href=\"/blog/dry-mouth/\">Dry Mouth Causes and Remedies</a>."),
]

CTA_TITLE = "Are you an Oral Medicine provider in Australia?"
CTA_TEXT = "Apply to be featured in our next update."

DISCLOSURE = "Practices in positions 1 to 3 are paid placements with do-follow links. Practices in positions 4 to 10 are listed editorially with no-follow links. Paid placement never affects positions 4 to 10."

SCHEMAS = []  # built by the template's _build_schemas() in manual workflow