"""Content for /australia/oral-medicine/ — Top 10 Oral Medicine in Australia.
Generated by service_pipeline.py (2026-08-30). Manually corrected with verified clinic data."""
import json

META_TITLE = "Top 10 Oral Medicine in Australia"
META_DESC = "Compare the top 10 oral medicine providers in Australia. Verified clinics, typical costs, FAQs and expert guidance to help you choose."
H1 = "Top 10 Oral Medicine in Australia"
BADGE = "Top 10 — Reviewed & Ranked"

INTRO = [
    "Oral medicine is the dental specialty concerned with the diagnosis and non-surgical management of conditions affecting the mouth, jaws and surrounding tissues. This includes oral mucosal diseases (such as lichen planus, ulcers and white patches), oral cancer screening, chronic facial pain, dry mouth (xerostomia), salivary gland disorders and oral manifestations of systemic disease. Oral medicine specialists work closely with GPs and other medical specialists to manage complex oral conditions.",
    "This ranking compares 10 Australian practices that offer oral medicine assessment and management across Sydney, Melbourne and beyond. We assessed verified addresses, phones, specialist expertise, diagnostic capability, pricing transparency and patient reviews, so you can compare providers before booking.",
    'Positions 1 to 3 are paid placements with do-follow links. Positions 4 to 10 are editorial selections with no-follow links. Browse our complete directory of <a href="/australia/">all dental services across Australia</a>. Read <a href="/methodology/">our methodology</a> and our <a href="/disclosures/">disclosures policy</a> for full transparency.',
]

WHEN_HEADING = "When Is Oral Medicine Care Needed?"
WHEN = [
    "You may need oral medicine care if you experience:",
    "Persistent mouth ulcers or sores that do not heal within 2–3 weeks, white or red patches in the mouth, chronic dry mouth, altered taste, difficulty swallowing, facial or jaw pain, burning mouth syndrome, or suspicious lumps or growths. Early assessment is important, particularly for lesions that do not resolve, as some oral conditions require specialist investigation and biopsy.",
    "<strong>Emergency alert:</strong> If you have severe pain, swelling that affects breathing or swallowing, or uncontrolled bleeding, call 000 or go to the nearest hospital emergency department immediately.",
]

WHEN_ALERT = "If you have severe pain, uncontrolled bleeding, or facial swelling that affects breathing or vision, call 000 or go to the nearest hospital emergency department immediately."

WHO_HEADING = "Which are the top 10 oral medicine providers in Australia?"
WHO_TOP10 = "The ten clinics below are ranked from 1 to 10. Ranks 1-3 are featured entries."

TOP10 = [
    {"rank": 1, "name": "Smile Solutions", "location": "Melbourne CBD, VIC", "featured": True, "rating": "4.8/5 (Google)", "pricing": "Specialist consult from $280", "hours": "Mon–Fri 8:00am–6:00pm, Sat 9:00am–5:00pm", "address": "Level 1, 220 Collins St, Manchester Unity Building, Melbourne VIC 3000", "phone": "(03) 9650 4920", "website": "https://www.smilesolutions.com.au", "body": ["Smile Solutions is one of Melbourne's largest dental practices, housing multiple specialists under one roof. Their oral medicine and oral pathology services include assessment of mucosal lesions, oral cancer screening, biopsy and referral pathways coordinated with medical specialists, all within a single multidisciplinary team.", "Located in the heritage Manchester Unity Building on Collins Street, the practice is open six days a week and easily accessible from Flinders Street Station."]},
    {"rank": 2, "name": "Clear Dental", "location": "Sydney CBD, NSW", "featured": True, "rating": "4.8/5 (Google)", "pricing": "Consultation from $95", "hours": "Mon–Fri 9:00am–6:00pm", "address": "131 Clarence Street, Sydney NSW 2000", "phone": "(02) 9456 6557", "website": "https://www.cleardental.com.au", "body": ["Clear Dental is a modern multi-location Sydney practice offering comprehensive oral assessment including mucosal examination, oral cancer screening and referral pathways for suspected oral pathology. Their experienced clinical team provides thorough, evidence-based care for patients with oral lesions or chronic oral conditions.", "With multiple locations across Sydney including Parramatta, Castle Hill and Rouse Hill, Clear Dental makes oral health assessment accessible across the greater Sydney area."]},
    {"rank": 3, "name": "Pitt St Dental Centre", "location": "Sydney CBD, NSW", "featured": True, "rating": "4.7/5 (Google)", "pricing": "Consultation from $110", "hours": "Mon–Fri 8:30am–5:30pm", "address": "Level 2, 70 Pitt St, Sydney NSW 2000", "phone": "(02) 8000 1832", "website": "https://www.pittstdentalcentre.com.au", "body": ["Pitt St Dental Centre is an established Sydney CBD practice offering comprehensive oral medicine assessment, including evaluation of mucosal conditions, oral cancer screening and soft tissue examination. The team provides careful investigation and clear referral pathways for patients with persistent oral lesions or symptoms.", "Located on Pitt Street in the heart of the Sydney CBD, the practice is a short walk from Wynyard and Town Hall stations. They offer thorough, evidence-based assessment in a professional setting."]},
    {"rank": 4, "name": "Hyde Park Dental Care", "location": "Sydney CBD, NSW", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Consultation from $100", "hours": "Mon–Fri plus selected Saturdays", "address": "Suite 10, Lower Level, Hyde Park Square, 227 Elizabeth Street, Sydney NSW 2000", "phone": "02 9267 9526", "website": "https://www.hydeparkdentalcare.com.au", "body": ["Hyde Park Dental Care is a modern practice located in Hyde Park Square in the Sydney CBD, offering comprehensive oral assessment including soft tissue examination, oral cancer screening and preventive oral medicine care. The team provides careful investigation of oral lesions and chronic conditions.", "Located at the corner of Elizabeth and Bathurst Streets, directly opposite Hyde Park, the clinic is easily accessible by train, bus and light rail."]},
    {"rank": 5, "name": "Dental and Skin", "location": "Bentleigh East, VIC", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Consultation from $130", "hours": "Mon–Fri 9:00am–5:30pm", "address": "778a Centre Rd, Bentleigh East VIC 3165", "phone": "03 9088 1118", "website": "https://www.dentalandskin.com.au", "body": ["Dental and Skin is a holistic practice in Melbourne's south-east offering oral medicine assessment alongside skin health care. The team provides thorough examination of oral mucosal conditions, oral cancer screening and a holistic approach to oral and systemic health, with clear referral pathways where specialist management is needed.", "Located on Centre Road in Bentleigh East, the practice is open six days a week with on-site parking."]},
    {"rank": 6, "name": "Macquarie Street Dental", "location": "Sydney CBD, NSW", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Consultation from $110", "hours": "Mon–Fri 8:30am–5:00pm", "address": "Level 4, 135 Macquarie St, Sydney NSW 2000", "phone": "(02) 9251 5999", "website": "https://www.macquariestreetdental.com.au", "body": ["Macquarie Street Dental is a well-established practice in Sydney's premier medical precinct, offering comprehensive oral assessment including soft tissue examination, oral pathology screening and preventive oral medicine care. The team provides careful investigation of oral lesions and chronic oral conditions, with referral pathways into the surrounding medical precinct.", "Located on Macquarie Street near Martin Place and St James stations, the practice is easily accessible by train and bus."]},
    {"rank": 7, "name": "Mosman Dental Surgery", "location": "Mosman, NSW", "featured": False, "rating": "4.9/5 (Google)", "pricing": "Consultation from $100", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "Suite 1D, 1 Spit Rd, Mosman NSW 2088", "phone": "(02) 9969 7433", "website": "https://www.mosmandentalsurgery.com.au", "body": ["Mosman Dental Surgery is a family-owned practice on Sydney's lower north shore offering comprehensive oral assessment, including soft tissue examination and oral cancer screening. The experienced team provides careful evaluation of oral lesions and chronic conditions, with appropriate referral pathways for specialist oral medicine care.", "Located on Spit Road in the heart of Mosman, the practice is known for its gentle approach and thorough, patient-focused care."]},
    {"rank": 8, "name": "Dental on Clarendon", "location": "South Melbourne, VIC", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Consultation from $100", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "383 Clarendon St, South Melbourne VIC 3205", "phone": "03 9690 3285", "website": "https://www.dentalonclarendon.com.au", "body": ["Dental on Clarendon is a modern family practice in South Melbourne offering comprehensive oral assessment, including soft tissue examination, oral cancer screening and preventive care. The experienced team provides careful investigation of oral lesions and chronic oral conditions, with clear referral pathways.", "Conveniently located on Clarendon Street with tram access and nearby parking, the practice is a popular choice for South Melbourne and inner-suburb residents."]},
    {"rank": 9, "name": "Precision Dental", "location": "Toowong, QLD", "featured": False, "rating": "4.8/5 (Google)", "pricing": "Consultation from $95", "hours": "Mon–Fri 8:30am–5:30pm, Sat 9:00am–1:00pm", "address": "33 Sherwood Rd, Toowong QLD 4066", "phone": "(07) 3870 3519", "website": "https://www.precisiondental.com.au", "body": ["Precision Dental is a well-regarded family practice in Toowong, Brisbane, offering comprehensive oral assessment including soft tissue examination and oral cancer screening. The experienced team provides careful evaluation of oral lesions and chronic conditions, with referral pathways to specialist oral medicine services.", "Conveniently located on Sherwood Road near Toowong Village, the practice is easily accessible by train, bus and car."]},
    {"rank": 10, "name": "Adelaide DentalCare", "location": "Adelaide CBD, SA", "featured": False, "rating": "4.7/5 (Google)", "pricing": "Consultation from $95", "hours": "Mon–Fri 8:30am–5:30pm", "address": "Level 1, 45 Grenfell St, Adelaide SA 5000", "phone": "(08) 8212 5976", "website": "https://www.adelaidedentalcare.com.au", "body": ["Adelaide DentalCare is a modern city practice in the heart of the Adelaide CBD, offering comprehensive oral assessment including soft tissue examination, oral cancer screening and preventive oral medicine care. The team provides careful investigation of oral lesions and chronic conditions, with appropriate referral pathways.", "Conveniently located on Grenfell Street with easy access from public transport, the practice is a popular choice for city workers and Adelaide residents."]},
]

COST_HEADING = "How Much Does Oral Medicine Care Cost in Australia?"
COST = [
    "The cost of an oral medicine consultation in Australia depends on whether you see a general dentist or a registered specialist in oral medicine, the complexity of the assessment and any diagnostic procedures required. Initial consultations typically range from $95 for a general assessment to $280+ for a specialist consultation.",
    "<strong>Funding Note:</strong> Medicare does not generally cover dental consultations, though some oral medicine procedures (such as biopsies arranged through medical pathways) may attract Medicare rebates. Private health insurance extras policies typically cover a percentage of the consultation fee. Biopsy and histopathology costs are usually quoted separately.",
]
COST_PRICES = [
    ("General dental consultation", "$50 – $120"),
    ("Comprehensive oral medicine assessment", "$100 – $280"),
    ("Specialist oral medicine consultation", "$250 – $400"),
    ("Oral cancer screening / soft tissue exam", "$80 – $200"),
    ("Mouth biopsy (surgical procedure)", "$300 – $800"),
    ("Histopathology laboratory fee", "$150 – $400"),
]
COST_AFTER = [
    'See our <a href="/blog/">dental costs guide</a> for full fee breakdowns.',
]

CHOOSE_HEADING = "How to Choose an Oral Medicine Provider in Australia"
CHOOSE_INTRO = "Ask these questions before you book."
CHOOSE_CRITERIA = [
    ("Is the practitioner a registered specialist in oral medicine?", "Oral medicine is a recognised dental specialty in Australia. Ask whether the treating practitioner is a registered specialist in oral medicine or a general dentist with experience in oral mucosal disease and soft tissue assessment."),
    ("What diagnostic equipment and procedures are available on site?", "Ask whether the practice can perform thorough soft tissue examination, oral cancer screening and biopsy on site, and whether histopathology samples are sent to an accredited laboratory for analysis."),
    ("Does the clinic offer bulk billing or transparent itemised fees?", "Oral medicine consultations are rarely bulk-billed, but a good practice will provide a written itemised quote covering the consultation and any diagnostic procedures before treatment begins."),
    ("Are the location and hours practical for follow-up care?", "Oral medicine conditions often require multiple follow-up visits. Choose a practice that is convenient to reach and offers appointment times that suit your schedule, including for monitoring of chronic conditions."),
    ("Does the practice collaborate with other specialists and your GP?", "Oral medicine often sits at the interface of dental and medical care. Ask whether the practice has established referral pathways with oral and maxillofacial surgeons, dermatologists, rheumatologists and GPs for coordinated management."),
]
CHOOSE_AFTER = []

METHODOLOGY_HEADING = "How We Ranked the Top 10 Oral Medicine Providers"
METHODOLOGY = [
    "We ranked these clinics using the criteria below."
]
METHODOLOGY_CRITERIA = [
    "Every clinic in this ranking was assessed against the same 8 criteria. Points were weighted towards verified data and patient value.",
    "Verified contact details — Practices with a confirmed full street address and live phone number scored highest.",
    "Oral medicine expertise — Specialist oral medicine, oral pathology and soft tissue assessment experience.",
    "Diagnostic capability — On-site biopsy, oral cancer screening and referral pathways.",
    "Pricing transparency — Published fee schedules, live price lists or clear itemised quotes before booking.",
    "Patient reviews and reputation — Quality and volume of Google and practice-published patient reviews.",
    "Location accessibility — CBD access, public transport, parking and suitability for follow-up care.",
    "Health fund and HICAPS processing — On-the-spot rebates and preferred provider arrangements.",
    "Multidisciplinary collaboration — Established pathways with medical and surgical specialists.",
    "Ratings change as patient feedback and practice details change. We re-verify clinic data periodically; if you spot an error, contact us so we can update this ranking.",
]
METHODOLOGY_AFTER = []

FAQ_HEADING = "Frequently Asked Questions"
FAQS = [
    ("What kind of dentist treats oral medicine conditions?", "Oral medicine is a dental specialty focused on the diagnosis and non-surgical management of conditions affecting the mouth, jaws and surrounding tissues. Registered oral medicine specialists, and some experienced general dentists with a focus on oral mucosal disease, assess and manage these conditions."),
    ("Do I need a referral from a GP to see an oral medicine specialist?", "You generally do not need a referral to see a dentist or oral medicine specialist in private practice. However, if your condition involves coordination with medical specialists, a referral from your GP can help share information and may be needed for Medicare-rebatable services."),
    ("Will my private health insurance cover oral medicine treatments?", "Most extras policies cover a percentage of dental consultation fees, which may include oral medicine assessments. Specialist consultations and procedures such as biopsies may attract higher benefits depending on your level of cover. Check your policy and ask your practice for an itemised quote."),
    ("How long does it take to get results from a mouth biopsy?", "If a biopsy is required, the tissue sample is sent to an accredited pathology laboratory for histopathological analysis. Results typically take 5–10 business days. Your practitioner will explain the findings and any recommended follow-up when results are available."),
    ("Is oral lichen planus contagious?", "No. Oral lichen planus is a chronic inflammatory condition thought to involve the immune system; it is not contagious. Many people with oral lichen planus have no symptoms and need only monitoring, while others may require treatment for discomfort or to manage flare-ups."),
    ("What causes recurrent mouth ulcers and how can I prevent them?", "Recurrent mouth ulcers (aphthous ulcers) can be triggered by stress, certain foods, hormonal changes, trauma, vitamin deficiencies or underlying health conditions. Keeping a diary of triggers, maintaining good oral hygiene and managing stress can help. Persistent or unusual ulcers should be assessed by a dentist."),
    ("What are the early signs of oral cancer I should look out for?", "Early signs include a sore or ulcer that does not heal within 2–3 weeks, a red or white patch, a lump or thickening, difficulty chewing or swallowing, persistent sore throat, or numbness in the mouth. If you notice any of these, see a dentist promptly for a thorough oral examination."),
]

CTA_TITLE = "Are you an Oral Medicine provider in Australia?"
CTA_TEXT = "Apply to be featured in our next update."

DISCLOSURE = "Practices in positions 1 to 3 are paid placements with do-follow links. Practices in positions 4 to 10 are listed editorially with no-follow links. Paid placement never affects positions 4 to 10."

SCHEMAS = []  # built by the template's _build_schemas() in manual workflow