# Generated by Django 6.0.7 on 2026-07-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='schema_json',
            field=models.TextField(blank=True, verbose_name='Schema.org JSON-LD (JSON list)'),
        ),
    ]
