# Generated by Django 6.0.7 on 2026-07-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Body (HTML)'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='schema_json',
            field=models.TextField(blank=True, verbose_name='Schema.org JSON-LD'),
        ),
    ]
