# Generated by Django 6.0.7 on 2026-07-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_body_blogindexpage_schema_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Body (HTML)'),
        ),
    ]
