# Generated by Django 6.0.7 on 2026-07-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author_bio',
            field=models.TextField(blank=True, verbose_name='Author Bio (HTML)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author_credentials',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
