# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credentials', models.CharField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True, verbose_name='Bio (HTML)')),
            ],
            options={
                'verbose_name_plural': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author_bio',
            field=models.TextField(blank=True, editable=False, verbose_name='Author Bio (HTML)'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author_credentials',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.author'),
        ),
    ]
