# Generated by Django 6.0.7 on 2026-07-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='schema_json',
            field=models.TextField(blank=True, verbose_name='Schema.org JSON-LD'),
        ),
    ]
