# Generated by Django 6.0.7 on 2026-07-07 18:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('faq', 5), ('stats', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'p', 'bold', 'italic', 'ol', 'ul', 'link', 'blockquote']}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('question', 2), ('answer', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'icon': 'list-ul'}), 6: ('wagtail.blocks.StructBlock', [[('number', 2), ('label', 2)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'table'})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_intro',
            field=models.TextField(blank=True, help_text='The intro paragraph shown in the hero section.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default="Australia's Most Comprehensive Dental Resource", max_length=255),
        ),
    ]
