# Generated by Django 6.0.7 on 2026-07-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_remove_homepage_hero_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='features',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='stats',
        ),
    ]
